import {StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import Colors from '../../redux/constants/colors';
import colors from '../../redux/constants/colors';

const styles = StyleSheet.create({
  carouselContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: Dimension.padding10,
    // paddingLeft: Dimension.margin10,
    paddingBottom: Dimension.padding10,
    position: 'relative',
  },
  header: {
    backgroundColor: Colors.RedThemeColor,
    borderBottomColor: '#C9C9C9',
    borderBottomWidth: 0.5,
    padding: Dimension.padding12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerIcon: {
    color: '#fff',
  },
  cartNav: {marginLeft: Dimension.margin16, position: 'relative'},
  itemsListView: {
    width: 14,
    height: 14,
    backgroundColor: '#fff',
    position: 'absolute',
    top: -6,
    right: -6,
    borderRadius: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemsListText: {
    color: colors.RedThemeColor,
    alignSelf: 'center',
    fontSize: 8,
    fontFamily: Dimension.CustomMediumFont,
  },
  LogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoImage: {
    width: Dimension.width55,
    height: Dimension.width22,
  },
  showTextStyle: {
    marginLeft: Dimension.margin8,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  smallLogo: {
    width: Dimension.width22,
    height: Dimension.width22,
    marginLeft: Dimension.margin10,
    marginVertical: Dimension.margin10,
    // borderWidth:1, borderColor:'red',
    // marginTop: -Dimension.margin12,
    // marginHorizontal:-Dimension.margin5,
  },
  nameOnHeader: {
    maxWidth: Dimension.width150,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomMediumFont,
  },
  searchView: {
    flexDirection: 'row',
    paddingVertical: Dimension.padding6,
    paddingHorizontal: Dimension.padding8,
    borderColor: '#cacaca',
    borderWidth: 1,
    borderRadius: Dimension.borderRadius8,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  voiceIconCss: {
    color: Colors.BlueText,
    fontSize: Dimension.font22,
    // position: 'absolute',
    // right: Dimension.margin12,
    // top: Dimension.margin10,
  },
  searcinputText: {
    fontSize: Dimension.font12,
    marginLeft: Dimension.margin15,
    fontFamily: Dimension.CustomRegularFont,
    color: Colors.lightGrayText,
    textAlignVertical: 'center',
    // borderRadius: 8,
    backgroundColor: '#fff',
    // justifyContent: 'center',
    // borderWidth: 1,
    // borderColor: '#C9C9C9',
    // width: '100%',
    // flex: 1,
    // position: 'relative',
    // paddingLeft: Dimension.padding40,
    // height: Dimension.height40,
  },
  searcinputTextBold: {
    fontSize: Dimension.font12,
    color: Colors.lightGrayText,
    textAlignVertical: 'center',
    borderRadius: 8,
    backgroundColor: '#fff',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C9C9C9',
    width: '100%',
    flex: 1,
    position: 'relative',
    paddingLeft: Dimension.padding40,
    height: Dimension.height40,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  searchIconWrap: {
    // position: 'absolute',
    // left: Dimension.margin20,
    // top: Dimension.margin12,
  },
  SearchIcon: {
    width: Dimension.height24,
    height: Dimension.width24,
    tintColor: Colors.PrimaryTextColor,
  },
});

export default styles;
