import {Dimensions, StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import colors from '../../redux/constants/colors';
import {left} from 'styled-system';

const styles = StyleSheet.create({
  selectAddPage: {flex: 1, position: 'relative'},
  emiAnimationText: {
    marginLeft: Dimension.margin10,
    height: Dimension.height20,
    backgroundColor: colors.bluelightshade,
    borderWidth: 1,
    borderColor: colors.blueShade,
    overflow: 'hidden',
    paddingLeft: Dimension.padding8,
    paddingRight: Dimension.padding8,
    paddingTop: Dimension.padding4,
    borderRadius: Dimension.borderRadius8,
  },
  animatedtext: {
    color: colors.blueShade,
    fontSize: Dimension.font11,
    textAlign: 'center',
    fontFamily: Dimension.CustomSemiBoldFont,
    height: Dimension.height20,
    alignSelf: 'center',
  },
  headerView: {
    zIndex: 1000,
    elevation: 1,
    flexDirection: 'row',
    height: 60,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#EFEFF4',
    paddingHorizontal: Dimension.padding10,
    justifyContent: 'space-between',
    position: 'relative',
    backgroundColor: '#fff',
  },
  filtHeading: {
    marginLeft: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font12,
    paddingTop: 5,
    color: colors.PrimaryTextColor,
  },
  headerFlex: {flexDirection: 'row'},
  bottomHeaderWrap: {backgroundColor: '#fff', marginTop: -3},
  bottomHeaderTop: {flexDirection: 'row'},
  textWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: Dimension.padding12,
  },
  headerTitle: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font12,
    color: colors.green2,
    textTransform: 'uppercase',
  },
  grayheaderTitle: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    textTransform: 'uppercase',
  },
  ProgressBar: {flexDirection: 'row', width: '100%'},
  greenLine: {backgroundColor: colors.green2, height: 2, marginVertical: 4},
  grayLine: {backgroundColor: colors.gray2, height: 2, marginVertical: 4},
  greenDot: {
    width: Dimension.padding10,
    height: Dimension.padding10,
    backgroundColor: colors.green2,
    borderRadius: Dimension.padding10,
  },
  grayDot: {
    width: Dimension.padding10,
    height: Dimension.padding10,
    backgroundColor: colors.gray2,
    borderRadius: Dimension.padding10,
  },
  Pwidth1: {width: '8%'},
  Pwidth2: {width: '38%'},
  checkOutPage: {paddingHorizontal: Dimension.padding12, flex: 1},
  headingWrap: {
    paddingHorizontal: 15,
    marginTop: 8,
    // flexDirection:'Column',
  },
  headingTitle: {
    paddingVertical: 15,
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
  },
  paymentElementWrap: {
    paddingHorizontal: 15,
  },
  paymentElementInner: {
    paddingVertical: 0,
    backgroundColor: '#fff',
    borderRadius: 6,
  },
  paymentElement: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Dimension.margin15,
    paddingHorizontal: Dimension.margin15,
    borderTopWidth: 1,
    borderTopColor: '#EFEFF4',
    // backgroundColor: '#fff',
  },
  paymentElementTxt: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    marginLeft: Dimension.margin15,
  },

  paymentWrap: {marginVertical: 15, marginHorizontal: 0},
  payHeading: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    paddingTop: Dimension.padding5,
    paddingBottom: Dimension.padding12,
    paddingVertical: Dimension.padding10,
    borderBottomWidth: 1,
    borderBottomColor: colors.ProductBorderColor,
  },

  headerView: {
    zIndex: 1000,
    elevation: 1,
    flexDirection: 'row',
    height: 60,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#EFEFF4',
    paddingHorizontal: Dimension.padding10,
    justifyContent: 'space-between',
    position: 'relative',
    backgroundColor: '#fff',
  },
  filtHeading: {
    marginLeft: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font12,
    paddingTop: 5,
    color: colors.PrimaryTextColor,
  },
  headerFlex: {flexDirection: 'row'},
  bottomHeaderWrap: {backgroundColor: '#fff', marginTop: -3},
  bottomHeaderTop: {flexDirection: 'row'},
  textWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: Dimension.padding12,
  },
  headerTitle: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font12,
    color: colors.green2,
    textTransform: 'uppercase',
  },
  grayheaderTitle: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    textTransform: 'uppercase',
  },
  ProgressBar: {flexDirection: 'row', width: '100%'},
  greenLine: {backgroundColor: colors.green2, height: 2, marginVertical: 4},
  grayLine: {backgroundColor: colors.gray2, height: 2, marginVertical: 4},
  greenDot: {
    width: Dimension.padding10,
    height: Dimension.padding10,
    backgroundColor: colors.green2,
    borderRadius: Dimension.padding10,
  },
  grayDot: {
    width: Dimension.padding10,
    height: Dimension.padding10,
    backgroundColor: colors.gray2,
    borderRadius: Dimension.padding10,
  },
  Pwidth1: {width: '8%'},
  Pwidth2: {width: '38%'},
  checkOutPage: {paddingHorizontal: Dimension.padding12, flex: 1},
  gstCard: {
    backgroundColor: '#fff',
    padding: Dimension.padding10,
    borderRadius: Dimension.borderRadius6,
    shadowColor: '#888',
    flexDirection: 'row',
    marginTop: 20,
    // marginBottom: 15,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 4,
  },
  checkBox: {marginRight: 15},
  getGstInvTitle: {
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font12,
    marginBottom: -Dimension.margin2,
    color: colors.PrimaryTextColor,
  },
  getGstInvSubTitle: {
    fontSize: Dimension.font11,
    color: colors.lightGrayText,
    fontFamily: Dimension.CustomRegularFont,
  },
  promoAppliedView: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: Dimension.margin4,
    marginBottom: Dimension.margin12,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: Dimension.padding15,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  promocode: {
    color: colors.green2,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  applyCouponWrap: {
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius6,
    paddingHorizontal: Dimension.padding12,
    marginBottom: Dimension.padding10,
    flexDirection: 'row',
    paddingVertical: Dimension.padding12,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  couponIcon: {
    color: colors.green2,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  applyText: {
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font16,
    paddingTop: 2,
    marginLeft: 20,
    color: colors.PrimaryTextColor,
  },
  leftPromoArea: {flexDirection: 'row', alignItems: 'center'},
  ticketIcon: {color: colors.green2, marginRight: Dimension.margin15},
  promoSubText: {
    color: colors.lightGrayText,
    fontSize: Dimension.font11,
    marginTop: -Dimension.margin2,
    fontFamily: Dimension.CustomRegularFont,
  },
  viewAllOffers: {flexDirection: 'row'},
  arrowrightIcon: {
    fontSize: Dimension.font24,
    marginRight: 10,
    color: colors.PrimaryTextColor,
  },
  payHeading: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    paddingHorizontal: Dimension.padding12,
    paddingVertical: Dimension.padding10,
    borderBottomWidth: 1,
    borderBottomColor: colors.ProductBorderColor,

    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    paddingHorizontal: Dimension.padding12,
    paddingTop: Dimension.padding2,
    paddingBottom: Dimension.padding12,
    borderBottomWidth: 1,
    borderBottomColor: colors.ProductBorderColor,
  },
  amountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.ProductBorderColor,
    paddingVertical: Dimension.padding8,
    paddingHorizontal: Dimension.padding12,
  },
  amtTextLabel: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
  },
  noBorder: {borderBottomWidth: 0},
  totalAmountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.ProductBorderColor,
    paddingVertical: Dimension.padding10,
    paddingHorizontal: Dimension.padding12,
  },
  amtText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomRobotoRegular,
    color: colors.PrimaryTextColor,
  },
  greenAmtText: {
    color: colors.GreenColor,
  },
  totalAmtTextLabel: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
  },
  totalAmtText: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomRobotoBold,
    color: colors.PrimaryTextColor,
  },

  redBtn: {
    backgroundColor: colors.RedThemeColor,
    height: 50,
    width: '50%',
    borderRadius: Dimension.borderRadius6,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  redBtnText: {
    color: '#fff',
    marginLeft: Dimensions.margin8,
    fontFamily: Dimension.CustomBoldFont,
    fontSize: Dimension.font16,
    marginTop: Dimension.margin2,
  },
  bottomAction: {
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: Dimension.padding5,
    justifyContent: 'space-between',
    position: 'absolute',
    width: '100%',
    bottom: 0,
    flex: 1,
  },
  leftAmt: {
    width: '50%',
    justifyContent: 'center',
    paddingLeft: Dimension.padding15,
  },
  amtWrap: {flexDirection: 'row'},
  payable: {
    color: colors.lightGrayText,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
  },
  infoIcon: {color: colors.BlueText, marginLeft: Dimension.padding10},
  totalAmtinBottom: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font18,
    fontFamily: Dimension.CustomRobotoBold,
  },
  checkoutPage: {paddingBottom: 70},
  card: {
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius6,
    // paddingHorizontal: Dimension.padding12,
    paddingVertical: Dimension.padding15,
    marginBottom: Dimension.padding10,
    paddingBottom: 0,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  addrTitle: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomMediumFont,
  },
  addrWrap: {
    marginTop: Dimension.margin15,
  },
  addrListWrap: {
    marginVertical: 12,
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius6,
    padding: Dimension.padding12,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 1,
  },
  addrCustName: {
    color: '#000',
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomBoldFont,
    marginBottom: 5,
  },
  fullAddr: {
    color: '#000',
    fontFamily: Dimension.CustomRegularFont,
    fontSize: Dimension.font11,
  },
  changeAddrBtn: {
    backgroundColor: colors.LightRedThemeColor,
    padding: 8,
    width: '100%',
    borderRadius: Dimension.borderRadius6,
    marginTop: Dimension.margin10,
  },
  changeAddrText: {
    color: colors.RedThemeColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    alignSelf: 'center',
  },
  selectAddPage: {flex: 1, position: 'relative'},
  scrollViewPg: {flex: 1, marginBottom: 60},
  parentWraper: {
    flexDirection: 'row',
    marginBottom: Dimension.margin,
    justifyContent: 'center',
    paddingTop: Dimension.padding10,
    paddingBottom: Dimension.padding20,
  },
  TopCatWrap: {
    alignItems: 'center',
    marginRight: Dimension.margin10,
    alignContent: 'center',
    marginTop: Dimension.margin5,
    flexDirection: 'row',
  },
  TopCatName: {
    color: '#6F6F6F',
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font8,
    textAlign: 'left',
    textTransform: 'capitalize',
    width: 54,
  },

  TopCatImgWrap: {
    backgroundColor: colors.ExtralightGrayText,
    borderRadius: 4,
    padding: 3,
    marginRight: Dimension.margin8,
  },

  TopCatImg: {
    height: Dimension.width18,
    width: Dimension.width18,
    tintColor: colors.lightGrayText,
  },
  redtextwithbg: {
    backgroundColor: colors.LightRedThemeColor,
    paddingVertical: Dimension.padding8,
    paddingHorizontal: Dimension.padding10,
    marginTop: -Dimension.margin10,
    marginLeft: Dimension.padding45,
    marginRight: Dimension.margin20,
    marginBottom: Dimension.margin10,
    fontSize: Dimension.font11,
    color: colors.RedThemeColor,
    borderRadius: Dimension.borderRadius4,
  },
  NetBankingWrap: {backgroundColor: '#fff', flexDirection: 'column'},
  netBankingData: {
    borderTopColor: colors.ProductBorderColor,
    flexDirection: 'row',
    alignItems: 'center',
    padding: Dimension.padding15,
    marginHorizontal: 0,
    borderTopWidth: 1,
    textAlign: 'left',
  },
  radioWrap: {marginTop: Dimension.margin5},
  rightArrowImg: {width: Dimension.width24, height: Dimension.width24},

  radioBtnTxt: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomMediumFont,
    color: colors.PrimaryTextColor,
    marginLeft: 20,
  },
  walletText: {
    color: 'red',
    fontSize: 12,
  },
  walletList: {
    borderTopColor: '#E7E7E7',
    flexDirection: 'row',
    alignItems: 'center',
    padding: Dimension.padding15,
    marginHorizontal: 0,
    borderTopWidth: 1,
  },
  walletListTxt: {
    fontSize: Dimension.font14,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomMediumFont,
    marginLeft: 20,
  },
  walletRedTxt: {
    color: 'red',
  },
  nbRedTxt: {
    color: 'red',
  },
  nbInnerCta: {
    backgroundColor: colors.ProductBorderColor,
    borderWidth: 1,
    borderColor: colors.ProductBorderColor,
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '85%',
    alignSelf: 'flex-end',
    paddingHorizontal: Dimension.padding15,
    paddingVertical: Dimension.padding10,
    marginRight: Dimension.margin15,
    borderRadius: 8,
    marginBottom: Dimension.margin10,
  },
  nbCtaTxt: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomMediumFont,
    marginTop: Dimension.margin4,
  },
  modalWrap: {
    paddingRight: 0,
    paddingBottom: 0,
    paddingTop: 0,
    paddingLeft: 0,
    margin: 0,
    backgroundColor: '#fff',
  },
  modalInnerWrap: {
    backgroundColor: '#fff',
  },
  modalInnerHeader: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 15,
  },
  modalHeaderTxt: {color: '#000', fontSize: 16, fontWeight: '600'},
  modalListWrap: {
    borderTopColor: '#E7E7E7',
    flexDirection: 'row',
    alignItems: 'center',
    padding: Dimension.padding15,
    marginHorizontal: 0,
    borderTopWidth: 1,
  },
  bankName: {
    fontSize: Dimension.font14,
    marginLeft: 20,
    top:2,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomMediumFont,
  },
  bankNameError: {
    color: 'red',
    fontSize:Dimension.font12,
    bottom:1,
    marginLeft:Dimension.margin20
  },
  modalListInnerWrap: {
    // alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  inputCss: {
    marginTop: 0,
    // marginTop: -Dimension.margin12,
    height: Dimension.height40,
    fontSize: Dimension.font14,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomRegularFont,
    width: '100%',
    // paddingLeft: Dimension.padding10,
    borderWidth: 1,
    borderColor: colors.lightGrayText,
    paddingHorizontal: 10,
    fontSize: Dimension.font14,
    color: colors.placeholderGray,
    borderRadius: Dimension.borderRadius8,
  },
  paytmUpiLogo: {
    width: Dimension.width70,
    height: Dimension.width20,
    marginTop: Dimension.margin15,
  },
  paytmUpiRoundLogo: {
    width: Dimension.width22,
    height: Dimension.width20,
    marginTop: Dimension.margin10,
    bottom:5
  },
  UpiRoundLogo: {
    width: Dimension.width22,
    height: Dimension.width25,
    marginTop: Dimension.margin1,
  },
  paytmUpiWrap: {
    paddingHorizontal: Dimension.padding15,
    paddingTop: Dimension.padding10,
    paddingBottom: Dimension.padding20,
  },
  support: {
    fontSize: Dimension.font12,
    marginTop: Dimension.margin15,
    color: '#606060',
  },
  UpiImg: {
    width: Dimension.width30,
    height: Dimension.width30,
    marginBottom: 10,
    textAlign: 'center',
  },
  supportImages: {
    flexDirection: 'row',
    marginTop: Dimension.margin10,
  },
  upiWrapper: {
    padding: Dimension.padding15,
    borderBottomWidth: 1,
    borderColor: colors.ProductBorderColor,
  },
  upiInput: {
    borderWidth: 1,
    borderColor: colors.lightGrayText,
    paddingHorizontal: 10,
    fontSize: Dimension.font14,
    color: colors.placeholderGray,
    borderRadius: Dimension.borderRadius8,
  },
  newinputfield: {
    position: 'relative',
    margin: 0,
    padding: 0,
    marginTop: -Dimension.margin20,
  },
  payTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalInnerWrapNB: {flex: 1},
  bankNameinModal: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomSemiBoldFont,
    paddingTop: Dimension.padding4,
    marginLeft: 10,
  },
  nbScrollBG: {backgroundColor: colors.brandbg},
  selectedbankTitle: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomMediumFont,
    color: colors.PrimaryTextColor,
    paddingHorizontal: Dimension.padding15,
    paddingBottom: Dimension.padding10,
  },
  secureWrap: {
    flexDirection: 'row',
    padding: Dimension.padding15,
    alignItems: 'flex-start',
  },
  secureText: {
    fontSize: Dimension.font11,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.lightGrayText,
    marginLeft: Dimension.margin10,
  },
  securePayImage: {width: Dimension.width20, height: Dimension.width20},
  walletWrap: {paddingBottom: Dimension.padding10},
  imageIconStyle: {width: Dimension.width20, height: Dimension.width20},
});

export default styles;
