import {StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import Colors from '../../redux/constants/colors';
import colors from '../../redux/constants/colors';
import {flex} from 'styled-system';

const styles = StyleSheet.create({
  leftProdImage: {
    width: Dimension.prdListViewImage,
    height: Dimension.prdListViewImage,
  },

  checkoutContainer: {backgroundColor: '#fff'},
  cartheader: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.2)',
  },
  title: {
    color: '#303030',
    // fontSize: Fonts.style.large.fontSize,
    fontFamily: 'roboto',
  },
  activityIndicator: {
    // backgroundColor: '#e7e7e7',
    // borderRadius: 8,
    // width: '100%',
    // marginHorizontal: 12,
    // marginBottom: 8,
    // justifyContent:'center',
    // alignSelf: 'center',
    height: 600,
  },
  // cricle: {
  //   height: Dimension.width14,
  //   width: Dimension.width10,
  //   backgroundColor: '#7DC559',
  //   borderRadius: Dimension.width14,
  //   borderColor: '#7DC559',
  //   borderWidth: 0.5,
  // },
  Line: {height: Dimension.height70, width: 2, backgroundColor: '#7DC559'},
  smallLine: {height: Dimension.height34, width: 2, backgroundColor: '#7DC559'},

  redCircle: {backgroundColor: '#E32E12', borderColor: '#E32E12'},
  redLine: {backgroundColor: '#E32E12'},

  //greenLine:{ backgroundColor:"#7DC559", borderColor:"#7DC559"},
  //greenCircle:{ backgroundColor:"#7DC559"},

  orangeLine: {backgroundColor: '#E8C516'},
  orangeCircle: {backgroundColor: '#E8C516', borderColor: '#E8C516'},

  grayCircle: {borderColor: '#8C8C8C', backgroundColor: '#fff'},
  grayLine: {backgroundColor: '#8C8C8C'},
  grayLineSmall: {backgroundColor: '#8C8C8C', height: Dimension.height20},

  //
  cartCardWrap: {
    borderRadius: Dimension.borderRadius6,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.accborder,
    paddingHorizontal: Dimension.padding10,
    paddingVertical: Dimension.padding15,
  },
  cartCardItem: {
    paddingTop: Dimension.padding10,
    paddingBottom: Dimension.padding10,
    paddingRight: Dimension.padding10,
    paddingLeft: Dimension.padding10,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  cartCardLeft: {marginRight: Dimension.margin15, flex: 1},
  cartCardBody: {flex: 3.5},
  cartImg: {width: 74, height: 74},
  ItemDesc: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: Colors.PrimaryTextColor,
    marginBottom: Dimension.margin8,
  },

  flexDir: {flexDirection: 'row', alignItems: 'center'},
  ItemBrand: {
    // fontSize: Fonts.style.medium.fontSize,
    marginTop: 1,
    color: 'rgba(48, 48, 48, .5)',
    fontFamily: 'roboto',
  },
  ItemBrandName: {
    // fontSize: Fonts.style.normal.fontSize,
    marginTop: 1,
    color: 'rgba(48, 48, 48, 1)',
    marginLeft: 10,
    fontFamily: 'roboto',
  },

  ItemSellPrice: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomRobotoBold,
    fontWeight: '700',
    color: Colors.PrimaryTextColor,
    marginTop: Dimension.margin5,
  },
  TopCatWrap: {
    backgroundColor: Colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.ProductBorderColor,
    padding: Dimension.padding15,
    marginBottom: Dimension.margin10,
    marginLeft: Dimension.margin10,
    marginRight: Dimension.margin10,
  },
  Quantity: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: Colors.PrimaryTextColor,
    marginLeft: Dimension.margin8,
    marginTop: Dimension.margin6,
  },
  footerCardItem: {
    flex: 1,
    borderTopColor: Colors.ProductBorderColor,
    borderTopWidth: 1,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    paddingTop: Dimension.padding10,
    paddingBottom: Dimension.padding10,
    paddingRight: Dimension.padding10,
    paddingLeft: Dimension.padding10,
  },
  WriteReviewBtn: {
    borderRadius: 4,
    paddingVertical: Dimension.padding2,
    justifyContent: 'center',
    alignContent: 'center',
    flex: 1,
    borderColor: Colors.ProductBorderColor,
  },
  WriteReviewBtnText: {
    color: Colors.white,
    alignSelf: 'center',
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomBoldFont,
  },
  viewallbtnWrap: {
    borderColor: '#D9232D',
    color: '#D9232D',
    height: 35,
    borderWidth: 2,
    paddingHorizontal: 8,
  },
  Viewbtntext: {
    color: '#D9232D',
    fontWeight: 'bold',
    // fontSize: Fonts.style.font12.fontSize,
    fontFamily: 'roboto',
  },
  AddToCartBtn: {
    backgroundColor: '#455B6324',
    borderRadius: 5,
    flex: 1,
    marginRight: Dimension.margin5,
    justifyContent: 'center',
  },
  AddToCartBtnText: {
    color: Colors.PrimaryTextColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    flex: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    paddingVertical: Dimension.padding15,
  },

  lastedupdatedText: {
    fontSize: Dimension.font10,
    color: Colors.lightGrayText,
    fontFamily: Dimension.CustomRegularFont,
    width: '50%',
  },
  lastupdatedate: {
    fontSize: Dimension.font10,
    color: Colors.PrimaryTextColor,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginRight: Dimension.margin10,
  },

  //new for new order status
  OrderStatusText: {
    fontSize: Dimension.font10,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: Colors.PrimaryTextColor,
  },
  orderDate: {
    fontSize: Dimension.font10,
    fontFamily: Dimension.CustomRegularFont,
    color: Colors.lightGrayText,
  },
  greenCircle: {
    width: Dimension.width12,
    height: Dimension.width12,
    borderRadius: Dimension.width12,
    backgroundColor: Colors.GreenColor,
    position: 'relative',
    left: -Dimension.padding6,
    borderWidth: 1,
    borderColor: Colors.ProductBorderColor,
  },
  greenLineSmall: {
    backgroundColor: '#7DC559',
    // height: Dimension.height20,
  },
  grayCircle: {
    width: Dimension.width12,
    height: Dimension.width12,
    borderRadius: Dimension.width12,
    backgroundColor: Colors.white,
    position: 'relative',
    left: -Dimension.padding6,
    borderWidth: 1,
    borderColor: Colors.ProductBorderColor,
  },
  greenFullLine: {
    backgroundColor: Colors.GreenColor,
    width: Dimension.width150,
    height: 2,
    marginTop: 5,
  },
  grayFullLine: {
    backgroundColor: Colors.ProductBorderColor,
    width: Dimension.width80,
    height: 2,
    marginTop: 5,
  },

  grayHalfLine: {
    backgroundColor: Colors.ProductBorderColor,
    width: Dimension.width80 / 2,
    height: 2,
    marginTop: 5,
  },
  greenHalfLine: {
    backgroundColor: Colors.GreenColor,
    width: Dimension.width80 / 2,
    height: 2,
    marginTop: 5,
  },

  LightRedBtn: {
    backgroundColor: Colors.LightRedThemeColor,
    borderRadius: 4,
    paddingHorizontal: Dimension.padding10,
    justifyContent: 'center',
    paddingVertical: Dimension.padding8,
  },
  LightRedBtnText: {
    color: Colors.RedThemeColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  leftCtas: {
    flexDirection: 'row',
    width: '70%',
  },
  GrayBtn: {
    backgroundColor: colors.grayOrderCta,
    borderRadius: Dimension.borderRadius4,
    paddingHorizontal: Dimension.padding10,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: Dimension.width80,
    marginRight: Dimension.margin10,
    width: '100%',
    paddingVertical: Dimension.padding8,
  },
  CnclBtn: {
    backgroundColor: colors.grayOrderCta,
    borderRadius: Dimension.borderRadius4,
    paddingHorizontal: Dimension.padding10,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: Dimension.width90,
    marginRight: Dimension.margin10,
    width: '100%',
    paddingVertical: Dimension.padding8,
  },
  GrayBtnText: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  helpCta: {
    color: Colors.RedThemeColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    alignSelf: 'center',
  },
  GetText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
  },
  updatedPriceBox: {
    width: '100%',
    backgroundColor: '#F7F7FA',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    padding: Dimension.padding10,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
  },
  updatepriceText: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font10,
    color: Colors.PrimaryTextColor,
  },
  Needhelp: {
    justifyContent: 'center',
    paddingVertical: Dimension.padding8,
  },
  NeedHelpBtnText: {
    color: Colors.PrimaryTextColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  NeedHelpCancelBtnText: {
    color: Colors.RedThemeColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },

  cConfirmedImg: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 200,
    height: 200,
  },
  cConfirmedText: {
    fontSize: Dimension.font18,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: '#299E22',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewOrderBtn: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    flex: 1,
    marginRight: Dimension.margin15,
    borderColor: Colors.RedThemeColor,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
  },
  viewOrderBtnText: {
    color: Colors.RedThemeColor,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    alignSelf: 'center',
    lineHeight: 36,
    justifyContent: 'center',
  },
  shopMoreBtn: {
    backgroundColor: Colors.RedThemeColor,
    borderRadius: 8,
    flex: 1,
    height: 36,
    justifyContent: 'center',
  },
  shopMoreBtnText: {
    color: '#FFF',
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    alignSelf: 'center',
    justifyContent: 'center',
    lineHeight: 36,
  },
  BuyNowBtn: {
    backgroundColor: Colors.LightRedThemeColor,
    borderRadius: 4,
    justifyContent: 'center',
    paddingHorizontal: Dimension.padding10,
    height: 30,
  },
  BuyNowBtnText: {
    color: Colors.RedThemeColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  orderedAddressWrap: {
    marginTop: Dimension.margin15,
  },

  addressName: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomBoldFont,
    color: Colors.PrimaryTextColor,
    justifyContent: 'space-between',
  },
  addressTitle: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomMediumFont,
    color: Colors.PrimaryTextColor,
    marginBottom: Dimension.margin10,
  },

  offerheader: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    justifyContent: 'center',
  },
  headerView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: '100%',
    paddingTop: Dimension.padding10,
    paddingBottom: Dimension.padding8,
  },
  cancleBtn: {
    width: Dimension.width24,
    height: Dimension.width24,
    marginRight: Dimension.margin10,
  },
  headerTitle: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: Colors.PrimaryTextColor,
    marginTop: Dimension.margin6,
    // paddingBottom:Dimension.padding5
  },
  cancelheading: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomMediumFont,
    color: Colors.PrimaryTextColor,
    marginTop: Dimension.margin15,
  },

  // fontWeight:'400',fontFamily:Dimension.CustomRobotoRegular,
  //fontFamily:Dimension.CustomRobotoBold,fontWeight:'bold',
  trackCardItem: {
    borderTopColor: Colors.ProductBorderColor,
    borderTopWidth: 1,
    position: 'relative',
    paddingLeft: Dimension.padding40,
    height: Dimension.height40,
  },
  dot: {
    width: Dimension.width12,
    height: Dimension.width12,
    borderRadius: Dimension.borderRadius30,
    backgroundColor: '#EFEFF4',
    left: Dimension.padding15,
    position: 'absolute',
  },
  line: {
    width: 1,
    bottom: 0,
    top: Dimension.height20,
    backgroundColor: '#EFEFF4',
    left: Dimension.padding20,
    position: 'absolute',
  },
  lastdot: {
    width: Dimension.width12,
    height: Dimension.width12,
    borderRadius: Dimension.borderRadius30,
    backgroundColor: Colors.green2,
    left: Dimension.padding15,
    position: 'absolute',
  },
  lastline: {
    width: 1,
    top: 0,
    bottom: Dimension.height20,
    backgroundColor: Colors.green2,
    left: Dimension.padding20,
    position: 'absolute',
  },
  cardTracttext: {
    fontSize: Dimension.font12,
    color: Colors.PrimaryTextColor,
    marginRight: Dimension.margin10,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  cardTractDate: {
    fontSize: Dimension.font12,
    color: Colors.lightGrayText,
    marginTop: -Dimension.margin4,
  },
  cardTracttextWhite: {
    fontSize: Dimension.font12,
    color: '#fff',
    marginRight: Dimension.margin10,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  cardTractDateWhite: {
    fontSize: Dimension.font12,
    color: '#fff',
    marginTop: -Dimension.margin1,
  },
  greentrackCardItem: {height: Dimension.height50, backgroundColor: '#299E22'},
  checkdot: {
    fontSize: Dimension.font18,
    borderRadius: Dimension.borderRadius30,
    left: Dimension.padding12,
    position: 'absolute',
    color: '#fff',
    zIndex: 2,
  },
  greenline: {
    backgroundColor: '#4AB31E',
    width: 1,
    bottom: 0,
    top: 0,
    left: Dimension.padding20,
    position: 'absolute',
    zIndex: 1,
  },
  tractTextItem: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
  },
  tractText: {
    fontSize: Dimension.font12,
    color: '#fff',
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  rightArrImg: {
    width: Dimension.width25,
    height: Dimension.width25,
    tintColor: '#fff',
  },
  interestedCard: {paddingVertical: Dimension.padding15},
  intHeading: {
    fontSize: Dimension.font14,
    color: Colors.PrimaryTextColor,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginBottom: Dimension.margin10,
  },
  greencheckdot: {
    fontSize: Dimension.font18,
    borderRadius: Dimension.borderRadius30,
    left: Dimension.padding12,
    position: 'absolute',
    color: '#299E22',
  },
  cardTracttextgreen: {
    fontSize: Dimension.font12,
    color: '#299E22',
    marginRight: Dimension.margin10,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  // buyagain: {
  //   marginLeft: 'auto',
  //   backgroundColor: Colors.RedThemeColor,
  //   paddingVertical: Dimension.padding8,
  //   paddingHorizontal: Dimension.padding15,
  //   borderRadius: Dimension.borderRadius4,
  //   width: 130,
  //   alignItems: 'center',
  //   flexDirection: 'row',
  // },
  buytext: {
    color: '#fff',
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  deliveredCardItem: {paddingVertical: Dimension.padding20, height: 'auto'},

  oDeatilsheaderFlex: {flexDirection: 'row'},
  oDeatilsheaderView: {
    zIndex: 1000,
    elevation: 1,
    flexDirection: 'row',
    height: 60,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#EFEFF4',
    paddingHorizontal: Dimension.padding10,
    justifyContent: 'space-between',
    position: 'relative',
    backgroundColor: '#fff',
  },
  oDeatilsfiltHeading: {
    marginLeft: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font12,
    paddingTop: 5,
    color: colors.PrimaryTextColor,
  },
  oDeatilRight: {
    flexDirection: 'row',
    marginRight: Dimension.margin10,
  },
  leftImageIcon: {
    width: Dimension.width24,
    height: Dimension.width24,
  },
  gapImageIcon: {
    marginRight: Dimension.margin20,
  },
  oDeatilsWraper: {
    backgroundColor: colors.white,
    padding: Dimension.margin15,
  },
  orderDeatilsCard: {
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius8,
    // paddingHorizontal: Dimension.padding12,
    // paddingVertical: Dimension.padding15,
    marginBottom: Dimension.padding15,
    // paddingBottom: 0,
    borderWidth: 1,
    borderColor: colors.accborder,

    // shadowColor: 'rgba(0,0,0,0.5)',
    // shadowOffset: {width: 0, height: 1},
    // shadowOpacity: 0.3,
    // shadowRadius: 2,
    // elevation: 3,
  },
  prodImageName: {flexDirection: 'row'},
  leftProdImage: {width: Dimension.width74, height: Dimension.height74},
  prodName: {
    // paddingLeft: Dimension.padding25,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,

    // width:Dimensions.get('window').width * 0.6,
  },
  orderProdName: {
    paddingLeft: Dimension.padding25,
    flexDirection: 'column',
    flex: 3.5,
    // justifyContent:'center',
    // alignItems: 'flex-start',
  },
  prodInnerImageName: {
    paddingHorizontal: Dimension.padding12,
    paddingVertical: Dimension.padding10,
    flexDirection: 'row',
    flex: 1,
  },
  prodPrice: {
    marginRight: Dimension.margin8,
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomRobotoBold,
    color: colors.PrimaryTextColor,
  },
  orderProdPriceQty: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Dimension.padding10,
  },
  prodQty: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
  },
  orderedWrap: {
    borderTopWidth: 1,
    borderTopColor: '#EFEFF4',
    paddingHorizontal: Dimension.padding15,
    paddingVertical: Dimension.padding15,
    // backgroundColor:colors.GreenColor,
  },
  verticalTrack: {
    borderLeftWidth: 1,
    borderLeftColor: colors.accborder,
    paddingLeft: Dimension.padding15,
  },
  trackItems: {
    paddingVertical: Dimension.padding5,
    paddingRight: -Dimension.padding30,
  },
  orderedGreydot: {
    width: Dimension.width8,
    height: Dimension.width8,
    borderRadius: Dimension.borderRadius16,
    backgroundColor: Colors.ExtralightGrayText,
    position: 'absolute',
    top: 0,
    left: -4,
  },
  activeTrackItems: {
    backgroundColor: colors.GreenColor,
    paddingRight: -Dimension.padding30,
    display: 'flex',
  },

  cancelItemCtaWrap: {
    marginTop: Dimension.margin10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.accborder,
    paddingHorizontal: Dimension.padding10,
    paddingVertical: Dimension.padding10,
    borderRadius: Dimension.borderRadius8,
  },
  hScrollHead: {
    marginBottom: Dimension.margin10,
    marginTop: Dimension.margin20,
  },
  hScrollHeadTxt: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
  },

  paymentWrap: {marginTop: Dimension.padding15, marginHorizontal: 0},
  payHeading: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
  },

  amountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.ProductBorderColor,
    paddingVertical: Dimension.padding10,
    paddingHorizontal: Dimension.padding12,
  },

  amtTextLabel: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
  },

  amtText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomRobotoRegular,
    color: colors.PrimaryTextColor,
  },
  greenAmtText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomRobotoRegular,
    color: colors.green2,
  },
  noBorder: {borderBottomWidth: 0},
  card: {
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius6,
    // paddingHorizontal: Dimension.padding10,
    // paddingVertical: Dimension.padding10,
    // marginBottom: Dimension.padding10,
    borderWidth: 1,
    borderColor: colors.accborder,
  },
  payHeadingContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.ProductBorderColor,
    paddingVertical: Dimension.padding15,
    paddingHorizontal: Dimension.padding12,
  },
  payHeadingRht: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
  },
  totalAmountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.ProductBorderColor,
    paddingVertical: Dimension.padding15,
    paddingHorizontal: Dimension.padding12,
  },

  totalAmtTextLabel: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
  },
  totalAmtText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomRobotoBold,
    color: colors.PrimaryTextColor,
  },

  cartCardItem: {
    paddingTop: Dimension.padding10,
    paddingBottom: Dimension.padding10,
    paddingRight: Dimension.padding10,
    paddingLeft: Dimension.padding10,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  addressName: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomBoldFont,
    color: colors.PrimaryTextColor,
    justifyContent: 'space-between',
  },
  addressData: {
    fontSize: Dimension.font10,
    fontFamily: Dimension.CustomRegularFont,
    color: Colors.PrimaryTextColor,
    marginTop: Dimension.margin5,
    justifyContent: 'space-between',
  },
  addressData: {
    fontSize: Dimension.font10,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
    marginTop: Dimension.margin5,
  },
  addressData: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
    marginTop: Dimension.margin5,
    justifyContent: 'space-between',
  },
  addressDetails: {
    flexDirection: 'column',
    borderRadius: 8,
    alignItems: 'flex-start',
  },
  addressBtn: {
    backgroundColor: colors.accborder,
    borderRadius: Dimension.borderRadius4,
    width: '30%',
    paddingHorizontal: Dimension.padding10,
    paddingVertical: Dimension.padding8,
  },
  addressBtnText: {
    color: colors.lightGrayText,
    fontSize: Dimension.font10,
    fontFamily: Dimension.CustomSemiBoldFont,
    alignSelf: 'center',
  },
  addressContent: {
    // paddingTop: Dimension.padding15,
    bottom: 0,
  },
  retPolicyHead: {
    marginTop: Dimension.margin15,
    marginBottom: Dimension.margin8,
  },
  retPolicyHeadTxt: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  oCommonWraper: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  oCommonWraperFst: {
    backgroundColor: colors.GreenColor,
    borderRadius: Dimension.borderRadius20,
    width: Dimension.width8,
    height: Dimension.height8,
  },
  oCommonWraperSec: {
    width: Dimension.width15,
    height: Dimension.height1,
    backgroundColor: colors.GreenColor,
  },
  oCommonWraperThrd: {
    width: Dimension.width15,
    height: Dimension.height1,
  },
  oCommonWraperForth: {
    borderRadius: Dimension.borderRadius20,
    borderWidth: 0.5,
    borderColor: '#000',
    width: Dimension.width8,
    height: Dimension.height8,
  },
  getStatusModalLeftWrap: {
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    // flex:1,
    // paddingTop:20,
  },
  getStatusModalLeftWrapFst: {
    width: '25%',
    alignSelf: 'flex-end',
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: Colors.lightGrayText,
  },
  getStatusModalLeftWrapSec: {
    width: '10%',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  getStatusModalLeftWrapThrd: {
    flexDirection: 'column',
    width: '50%',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  getStatusModalLeftWrapThrdF: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: Colors.PrimaryTextColor,
    alignSelf: 'flex-start',
  },
  getStatusModalLeftWrapThrdS: {
    fontSize: Dimension.font10,
    fontFamily: Dimension.CustomRegular,
    color: Colors.PrimaryTextColor,
    opacity: 0.8,
    alignSelf: 'flex-start',
  },
  getStatusModalLeftWrapThrdT: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: Colors.PrimaryTextColor,
    alignSelf: 'flex-start',
  },
  TrackKnowModalWrap: {
    flex: 1,
    // padding: Dimension.padding20,
    backgroundColor: '#fff',
    marginVertical: -Dimension.margin18,
    marginHorizontal: -Dimension.margin18,
  },
  trackHeadSection: {
    marginTop: Dimension.margin20,
    marginBottom: Dimension.margin60,
    paddingHorizontal: Dimension.margin20,
  },
  trackHeadSectionTxt: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: Colors.PrimaryTextColor,
  },

  row: {flexDirection: 'row'},
  orderedTopCatWrap: {
    alignItems: 'center',
    marginRight: Dimension.margin15,
    backgroundColor: '#fff',
    alignContent: 'center',
    padding: Dimension.padding5,
    flexDirection: 'row',
    width: Dimension.width90,
    borderWidth: 1,
    borderColor: colors.accborder,
    borderRadius: Dimension.borderRadius8,
  },
  twoLineCatName: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginLeft: Dimension.margin5,
  },
  TopCatName: {
    color: colors.blueShade,
    fontFamily: Dimension.CustomRegularFont,
    fontSize: Dimension.font10,
    textAlign: 'center',
  },

  TopCatImgWrap: {
    backgroundColor: colors.LightRedThemeColor,
    borderRadius: 4,
    padding: Dimension.padding3,
    marginRight: Dimension.margin8,
  },

  TopCatImg: {height: Dimension.width24, width: Dimension.width24},

  orderedTrackCardItem: {
    borderTopColor: colors.ProductBorderColor,
    borderTopWidth: 1,
    paddingLeft: Dimension.padding10,
    height: Dimension.height50,
    flexDirection: 'row',
    alignItems: 'center',
  },

  orderedDot: {
    width: Dimension.width14,
    height: Dimension.width14,
    borderRadius: Dimension.borderRadius30,
    backgroundColor: '#EFEFF4',
    marginLeft: Dimension.margin6,
    // position: 'absolute',
  },
  cancelledDot: {
    width: Dimension.width12,
    height: Dimension.width12,
    borderRadius: Dimension.borderRadius30,
    marginLeft: Dimension.padding6,

    // position: 'absolute',
  },

  Orderedline: {
    width: 1,
    bottom: 0,
    top: Dimension.height20,
    backgroundColor: '#EFEFF4',
    left: Dimension.padding20,
    position: 'absolute',
  },

  lastdot: {
    width: Dimension.width12,
    height: Dimension.width12,
    borderRadius: Dimension.borderRadius30,
    backgroundColor: colors.green2,
    left: Dimension.padding15,
    position: 'absolute',
  },
  lastline: {
    width: 1,
    top: 0,
    bottom: Dimension.height20,
    backgroundColor: colors.green2,
    left: Dimension.padding20,
    position: 'absolute',
  },
  orderedCardTractWrap: {flexDirection: 'row', alignItems: 'center'},
  orderedCardTracttext: {
    fontSize: Dimension.font12,
    marginTop: Dimension.margin4,
    color: colors.PrimaryTextColor,
    marginRight: Dimension.margin10,
    marginLeft: Dimension.margin12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  orderedCardTractDate: {
    color: colors.lightGrayText,
    marginTop: Dimension.margin4,
    fontSize: Dimension.font11,
    fontFamily: Dimension.CustomRegularFont,
  },

  orderedcardTracttextWhite: {
    fontSize: Dimension.font11,
    color: '#fff',
    marginRight: Dimension.margin5,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginTop: Dimension.margin4,
  },
  orderedCardTractDateWhite: {
    fontSize: Dimension.font11,
    marginTop: Dimension.margin4,
    fontFamily: Dimension.CustomRegularFont,
    color: '#fff',
  },

  orderedGreentrackCardItem: {
    paddingVertical: Dimension.padding16,
    backgroundColor: '#299E22',
    borderBottomLeftRadius: Dimension.borderRadius8,
    borderBottomRightRadius: Dimension.borderRadius8,
    // justifyContent: 'center',
  },

  orderedCheckdot: {
    borderRadius: Dimension.borderRadius16,
    left: Dimension.padding5,
    position: 'absolute',
    zIndex: 12,
    paddingHorizontal: Dimension.padding10,
    paddingVertical: Dimension.padding10,
    color: '#fff',
    fontSize: Dimension.font18,
  },
  greenline: {
    backgroundColor: '#4AB31E',
    width: 1.5,
    bottom: Dimension.padding20,
    top: 0,
    height: 25,
    left: Dimension.padding20,
    position: 'absolute',
    zIndex: 1,
  },
  tractTextItem: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
  },
  tractText: {
    fontSize: Dimension.font12,
    color: '#fff',
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  orderedRightArrImg: {
    width: Dimension.width24,
    height: Dimension.width24,
    tintColor: '#fff',
  },
  interestedCard: {paddingVertical: Dimension.padding15},
  intHeading: {
    fontSize: Dimension.font14,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginBottom: Dimension.margin10,
  },
  greencheckdot: {
    fontSize: Dimension.font18,
    borderRadius: Dimension.borderRadius30,
    left: Dimension.padding12,
    position: 'absolute',
    color: '#299E22',
  },
  cardTracttextgreen: {
    fontSize: Dimension.font12,
    color: '#299E22',
    marginRight: Dimension.margin10,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  buyagain: {
    alignSelf: 'flex-end',
    marginTop: -Dimension.margin40,
    marginBottom: 10,
    marginRight: Dimension.margin15,
    backgroundColor: colors.RedThemeColor,
    flexDirection: 'row',
    paddingVertical: Dimension.padding8,
    paddingHorizontal: Dimension.padding15,
    borderRadius: Dimension.borderRadius4,
    // width: 130,
    alignItems: 'center',
  },
  buytext: {
    color: '#fff',
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  deliveredCardItem: {paddingVertical: Dimension.padding20, height: 'auto'},
  greenStripWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  greenStripLft: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: Dimension.padding40,
  },
  greenStripRht: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingRight: Dimension.padding10,
  },
  orderedReviewWrap: {
    borderTopColor: colors.ProductBorderColor,
    borderTopWidth: 1,
    padding: Dimension.padding15,
  },
  orderedReviewHead: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomBoldFont,
    color: colors.BoldgreenText,
  },
  orderedText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRobotoRegular,
    color: colors.PrimaryTextColor,
    marginTop: Dimension.margin5,
  },
  orderedStarCta: {
    marginTop: Dimension.margin15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderedStarLft: {
    flexDirection: 'row',
  },
  orderedStar: {
    marginRight: Dimension.margin6,
    color: colors.yellowShade,
    fontSize: Dimension.font26,
  },
  orderedReviewCta: {
    backgroundColor: colors.LightRedThemeColor,
    borderRadius: Dimension.borderRadius6,
  },
  orderedReviewCtaTxt: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRobotoBold,
    color: colors.RedThemeColor,
    paddingHorizontal: Dimension.padding15,
    paddingVertical: Dimension.padding8,
  },
});

export default styles;
