import {StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import colors from '../../redux/constants/colors';

const styles = StyleSheet.create({
  btnSelected: {
    borderColor: colors.RedThemeColor,
    borderWidth: 1,
    paddingHorizontal: Dimension.padding12,
    paddingVertical: Dimension.padding8,
    marginRight: Dimension.margin10,
    backgroundColor: 'rgba(244, 225, 229, 1)',
    borderRadius: Dimension.borderRadius6,
  },
  sizeBtn: {
    borderColor: colors.ProductBorderColor,
    borderWidth: 1,
    paddingHorizontal: Dimension.padding12,
    paddingVertical: Dimension.padding8,
    marginRight: Dimension.margin10,
    borderRadius: Dimension.borderRadius6,
  },
  sizetext: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
  },
  sizetextSelected: {
    color: colors.RedThemeColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  inactiveAttrBtnText: {
    color: colors.ExtralightGrayText,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  inactiveAttrBtn: {
    backgroundColor: '#e3e3e3',
    borderColor: '#fff',
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginRight: 10,
    borderRadius: 4,
    opacity: 1,
  },
  sizebtnWrap: {flexDirection: 'row'},
  reviewerTitle: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginBottom: Dimension.margin2,
  },
  reviewerText: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomRegularFont,
    marginBottom: Dimension.margin2,
  },

  ShowReviewInnerWrap: {
    paddingVertical: Dimension.padding10,
    borderTopWidth: 1,
    borderTopColor: colors.ProductBorderColor,
    borderStyle: 'dashed',
    borderRadius: 1,
  },
  ShowReviewWrap: {marginTop: Dimension.margin10},

  normalText: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomRegularFont,
    marginTop: Dimension.margin10,
  },
  PrdName: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomBoldFont,
  },
  PdpDetailWrap: {
    paddingHorizontal: Dimension.padding15,
    backgroundColor: '#fff',
    paddingVertical: Dimension.paddin2,
  },
  topratingWrap: {
    position: 'absolute',
    bottom: Dimension.padding10,
    left: Dimension.padding15,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ratingGreenWrap: {
    backgroundColor: colors.GreenColor,
    borderRadius: Dimension.borderRadius4,
    justifyContent: 'center',
    marginRight: Dimension.margin5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Dimension.padding5,
  },
  starIcon: {
    color: '#fff',
    fontSize: Dimension.font8,
    justifyContent: 'center',
    textAlignVertical: 'center',
  },
  starText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomBoldFont,
    color: '#fff',
    paddingTop: 2,
    marginRight: 3,
  },
  NooFReviewText: {
    fontSize: Dimension.font11,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.lightGrayText,
  },

  row: {flexDirection: 'row'},
  reviewWrap: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: Dimension.padding15,
  },
  bigstarIcon: {color: colors.yellowShade, fontSize: 130},
  // StarRatingText:{
  //    lineHeight: Platform.OS === 'ios' ? Dimension.height96 : 20,
  //     alignSelf:'center', position:"absolute", color:"#fff", fontSize:Dimension.font18,fontFamily:Dimension.CustomSemiBoldFont,alignItems:"center",justifyContent:'center',left:0,top:0,width:Dimension.width100, marginLeft:0,height:Dimension.height96,textAlignVertical:'center',textAlign:'center',marginTop:Dimension.margin5
  // },
  StarRatingText: {
    lineHeight: Platform.OS === 'ios' ? Dimension.height96 : null,
    color: colors.ratingColor,
    fontSize: Dimension.font30,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  starIconLeft: {
    color: colors.ratingColor,
    fontSize: Dimension.font26,
    marginLeft: Dimension.margin5,
    marginTop: -6,
  },
  ratingText: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font14,
    marginRight: 10,
    fontFamily: Dimension.CustomRegularFont,
  },
  ratingLine: {
    width: '100%',
    backgroundColor: '#EDEDED',
    height: 10,
    borderRadius: 2,
    minWidth: 160,
  },
  SelectRatingLine: {
    height: 10,
    borderRadius: 2,
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  greenShade: {backgroundColor: '#309615'},
  LightGreenShade: {backgroundColor: '#6BCF1B'},
  YellowShade: {backgroundColor: '#FDB92C'},
  OrangeShade: {backgroundColor: '#F5681E'},
  RedShade: {backgroundColor: '#FF1818'},
  WriteReviewBtn: {
    backgroundColor: colors.PrimaryTextColor,
    borderRadius: 8,
    justifyContent: 'center',
    alignContent: 'center',
    flex: 1,
    marginTop: Dimension.margin15,
    height: Dimension.height40,
  },
  WriteReviewBtnText: {
    color: colors.white,
    alignSelf: 'center',
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomBoldFont,
  },
  // normalText:{fontSize:Dimension.font12,color:colors.PrimaryTextColor,fontFamily:Dimension.CustomRegularFont,paddingVertical:Dimension.padding10,flex:1},

  lightText: {
    fontSize: Dimension.font12,
    color: colors.lightGrayText,
    fontFamily: Dimension.CustomRegularFont,
    marginBottom: Dimension.margin15,
    alignSelf: 'center',
  },

  starIcon: {
    color: colors.ratingColor,
    fontSize: Dimension.font11,
  },
  reviewerName: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomRegularFont,
    marginBottom: Dimension.margin2,
  },
  reviewerDate: {
    fontSize: Dimension.font12,
    color: colors.lightGrayText,
    fontFamily: Dimension.CustomRegularFont,
    marginBottom: Dimension.margin2,
  },
  reviewerTitle: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginBottom: Dimension.margin2,
  },
  reviewerText: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomRegularFont,
    marginBottom: Dimension.margin2,
  },

  ShowReviewInnerWrap: {
    paddingVertical: Dimension.padding10,
    borderTopWidth: 1,
    borderTopColor: colors.ProductBorderColor,
    borderStyle: 'dashed',
    borderRadius: 1,
    marginTop: Dimension.margin10,
  },
  dashedBorder: {
    borderWidth: 1,
    borderColor: colors.ProductBorderColor,
    borderStyle: 'dashed',
    borderRadius: 1,
  },
  ShowReviewWrap: {},

  reviewImg: {
    width: 80,
    height: 80,
    borderRadius: 4,
    marginRight: Dimension.margin10,
    marginTop: Dimension.margin5,
  },
  normalText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
  },
  grayText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.lightGrayText,
    alignSelf: 'center',
  },
  SectionTitleText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    textTransform: 'capitalize',
  },
  SectionTitleWrap: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginBottom: Dimension.margin15,
  },
  ViewAllBtn: {
    backgroundColor: colors.LightRedThemeColor,
    paddingHorizontal: Dimension.padding20,
    paddingVertical: Dimension.padding5,
    borderRadius: 4,
  },
  ViewAllBtnText: {
    textTransform: 'uppercase',
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomBoldFont,
    color: colors.RedThemeColor,
  },
  productDetail: {
    marginTop: Dimension.margin10,
    backgroundColor: '#fff',
  },
  sectionDetailTitle: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    paddingHorizontal: Dimension.padding12,
    paddingVertical: Dimension.padding10,
  },
  bottomActions: {
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#EFEFF4',
    padding: Dimension.padding5,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  actionBtn: {
    height: Dimension.height40,
    width: '48%',
    borderRadius: Dimension.borderRadius4,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addtocartbtn: {backgroundColor: '#fff'},
  buynowbtn: {backgroundColor: colors.RedThemeColor},
  actionText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomBoldFont,
  },
  cartIcon: {
    fontSize: Dimension.font18,
    marginTop: -Dimension.margin2,
    color: colors.RedThemeColor,
    marginRight: 10,
  },
  addtoCartText: {color: colors.RedThemeColor},
  buyNowText: {color: '#fff'},
  productTag: {
    maxWidth: Dimension.width100,
    width: '100%',
    top: Dimension.margin10,
    zIndex: 1,
    left: 0,
    position: 'absolute',
    paddingTop: Dimension.padding5,
  },
  tag: {width: Dimension.width80, height: Dimension.height28},
  productImageCarousel: {
    paddingBottom: Dimension.padding20,
    backgroundColor: '#fff',
    position: 'relative',
  },
  addToWishlist: {
    position: 'absolute',
    right: Dimension.padding15,
    top: Dimension.padding20,
    zIndex: 1,
    borderWidth: 1,
    borderColor: colors.ProductBorderColor,
    // width: Dimension.width32,
    // height: Dimension.width32,
    width: Dimension.width30,
    height: Dimension.width30,
    borderRadius: Dimension.borderRadius4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wishlistIcon: {
    color: colors.ExtralightGrayText,
    // width: 50,
    // height: 50,
  },
  redWishlistIcon: {
    color: colors.RedThemeColor,
  },
  shareOnSM: {right: Dimension.padding15, top: Dimension.width65},
  similarProductIcon: {top: 'auto', bottom: 0},
  similarPrdBtnIcon: {
    tintColor: '#000',
    width: Dimension.width18,
    height: Dimension.width18,
  },
  priceNQty: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: Dimension.padding10,
    flex: 1,
  },
  priceArea: {width: '62%'},
  qtyCol: {paddingTop: Dimension.padding4},
  tagWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: Dimension.padding10,
  },
  trend: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.LightRedThemeColor,
    borderRadius: Dimension.borderRadius4,
    paddingVertical: Dimension.padding5,
    paddingHorizontal: Dimension.padding8,
  },
  trendIcon: {color: colors.RedThemeColor, marginRight: 5},
  trendText: {
    color: Dimension.RedThemeColor,
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font11,
    color: colors.RedThemeColor,
  },
  activityIndicator: {
    height:'90%',
    alignSelf: 'center',
    marginTop: Dimension.margin35,
    position:'relative',
  },
  moreFromTabs: {
    backgroundColor: '#fff',
    borderBottomColor: '#e7e7e7',
    borderBottomWidth: 0.6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Dimension.padding12,
  },
  MoreTitle: {
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font14,
    color: '#000',
  },
  keyFeaturesView: {
    borderTopColor: '#e7e7e7',
    borderTopWidth: 1,
    padding: Dimension.margin12,
  },
  reviewArea: {
    padding: Dimension.padding12,
    marginTop: Dimension.margin12,
    backgroundColor: '#fff',
  },
  reviewAreaWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  halfWidthArea: {
    width: '50%',
  },
  greenratingArea: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  qandA: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Dimension.margin5,
  },
  qandAHeading: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: '#D9232D',
  },
  noQuestWrap: {
    padding: Dimension.padding12,
    marginTop: Dimension.margin12,
    backgroundColor: '#fff',
  },
  moreFromItem: {
    marginTop: Dimension.margin12,
  },
  prodDetailPage: {paddingBottom: 60, flex: 1},
  reviewModal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Dimension.margin5,
    alignItems: 'center',
  },
  viewAllReviews: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: '#D9232D',
  },
  reviewRatingWrap: {
    padding: Dimension.padding12,
    marginTop: Dimension.margin12,
    backgroundColor: '#fff',
  },
  deliveryCheckWrap: {
    backgroundColor: '#fff',
    marginTop: Dimension.margin10,
    padding: Dimension.padding12,
  },
  deliveryHeadingText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    marginBottom: Dimension.margin15,
  },
  deliveryCheckInnerArea: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checkText: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locPinIcon: {color: colors.RedThemeColor, marginRight: 15},
  checkTitle: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  checkSubTitle: {
    fontSize: Dimension.font11,
    color: colors.lightGrayText,
    fontFamily: Dimension.CustomRegularFont,
  },
  checkbtn: {
    backgroundColor: colors.RedThemeColor,
    paddingHorizontal: Dimension.padding20,
    height: 35,
    justifyContent: 'center',
    borderRadius: Dimension.borderRadius4,
  },
  checkbtnText: {
    color: '#fff',
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  // Modal SimilarProducts Style
  modalWrap: {
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    margin: 0,
  },
  modalInner: {
    width: Dimension.SCREEN_WIDTH,
    bottom: 0,
    position: 'absolute',
    backgroundColor: '#fff',
    // borderRadius: Dimension.borderRadius10,
    borderTopRightRadius:Dimension.borderRadius10,
    borderTopLeftRadius:Dimension.borderRadius10,
  },
  modalHeaderFlex: {
    flexDirection: 'row',
    paddingHorizontal: Dimension.padding15,
    paddingVertical: Dimension.padding12,
    justifyContent: 'space-between',
  },
  modalHeading: {
    marginLeft: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font14,
    paddingTop: 5,
    color: colors.PrimaryTextColor,
  },
  scrollViewWrap: {
    paddingHorizontal: Dimension.padding15,
    paddingVertical: Dimension.padding10,
  },
  smproductCard: {
    width: Dimension.width130,
    borderRadius: Dimension.borderRadius6,
    borderColor: colors.ProductBorderColor,
    borderWidth: 1,
    marginRight: Dimension.padding10,
    paddingVertical: Dimension.padding10,
    paddingHorizontal: Dimension.padding12,
  },
  prodImage: {width: '100%'},
  prodTitle: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    marginBottom: Dimension.margin10,
  },
  bybrand: {
    color: colors.lightGrayText,
    fontSize: Dimension.font11,
    marginBottom: 5,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  percentOff: {flexDirection: 'row', alignItems: 'center', marginBottom: -5},
  offPrice: {
    fontSize: Dimension.font11,
    color: 'rgba(43, 43, 43, 0.5)',
    fontFamily: Dimension.CustomRobotoRegular,
    marginTop: -4,
    textDecorationLine: 'line-through',
  },
  greenText: {
    fontSize: Dimension.font12,
    color: colors.ratingColor,
    fontFamily: Dimension.CustomBoldFont,
    paddingLeft: Dimension.padding10,
  },
  mainPrice: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomRobotoBold,
    color: colors.PrimaryTextColor,
  },
  //EMI Available Modal
  emiModalWrap: {
    paddingRight: 0,
    paddingBottom: 0,
    paddingTop: 0,
    paddingLeft: 0,
    margin: 0,
    height: Dimension.SCREEN_HEIGHT,
    backgroundColor: '#fff',
  },
  emiModalInner: {
    width: Dimension.SCREEN_WIDTH,
    bottom: 0,
    top: 0,
    backgroundColor: colors.brandbg,
    flex: 1,
  },
  emiModalHeaderFlex: {
    flexDirection: 'row',
    paddingHorizontal: Dimension.padding15,
    paddingVertical: Dimension.padding12,
  },
  emiModalHeading: {
    marginLeft: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font14,
    paddingTop: 2,
    color: colors.PrimaryTextColor,
  },
  list: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 15,
    paddingHorizontal: Dimension.margin15,
  },
  dotIcon: {marginRight: 12, marginTop: 4},
  seeHIW: {
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius4,
    padding: Dimension.padding15,
    borderWidth: 1,
    borderColor: colors.ProductBorderColor,
    flexDirection: 'row',
    marginHorizontal: Dimension.margin15,
    justifyContent: 'space-between',
  },
  seeHIWLeftArea: {flexDirection: 'row', alignItems: 'center'},
  hiwText: {paddingLeft: 12},
  hiwTitleText: {
    fontSize: Dimension.font12,
    marginBottom: -4,
    fontFamily: Dimension.CustomMediumFont,
  },
  hiwSubTitleText:{fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,},
  dropIcon: {marginTop: 2},
  suitabletext: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    paddingVertical: Dimension.padding12,
    fontFamily: Dimension.CustomMediumFont,
    borderBottomColor: colors.ProductBorderColor,
    borderBottomWidth: 1,
    paddingHorizontal: Dimension.margin15,
  },
  CCDCBtnWrap: {
    paddingVertical: Dimension.padding15,
    flexDirection: 'row',
    paddingHorizontal: Dimension.padding15,
  },
  cardTab: {
    height: 45,
    marginRight: 15,
    paddingHorizontal: Dimension.padding15,
    borderColor: colors.ProductBorderColor,
    borderWidth: 1,
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTabActive: {
    height: 45,
    marginRight: 15,
    paddingHorizontal: Dimension.padding15,
    borderColor: colors.RedThemeColor,
    borderWidth: 1,
    backgroundColor: colors.LightRedThemeColor,
    borderRadius: Dimension.borderRadius8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardActiveText: {
    color: colors.RedThemeColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  cardText: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  whiteBox: {
    backgroundColor: '#fff',
    paddingVertical: Dimension.padding15,
    borderBottomWidth: 1,
    borderBottomColor: colors.ProductBorderColor,
    paddingHorizontal: Dimension.padding15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bankNameWrap: {borderTopWidth: 1, borderTopColor: colors.ProductBorderColor},
  bankNameText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomMediumFont,
  },
  collapseArea: {padding: Dimension.padding15},
  planTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  planText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  planDetail: {
    borderWidth: 1,
    borderColor: colors.ProductBorderColor,
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius6,
    marginBottom: 15,
  },
  planRow: {
    paddingHorizontal: Dimension.padding15,
    paddingVertical: Dimension.padding10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  planPrice: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRobotoRegular,
  },
  planTextPrice: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
  },
  greenTextPA: {color: colors.GreenColor},
  noteText: {
    fontSize: Dimension.font11,
    fontFamily: Dimension.CustomRegularFont,
  },
  boldText: {fontFamily: Dimension.CustomSemiBoldFont},
  termsParaView: {
    paddingHorizontal: Dimension.padding15,
    marginBottom: Dimension.margin10,
  },
  termsTextPara: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    marginBottom: 10,
  },
  listText:{fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,},
  EmiMediumBoldText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomMediumFont,
  },
  EmiBoldText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRobotoBold,
  },
  termsHeading: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomSemiBoldFont,
    paddingTop: Dimension.padding10,
  },
  listWrap: {
    marginHorizontal: -Dimension.margin15,
    paddingRight: Dimension.padding15,
  },
  //Coupon & Offers Modal
  couponModalWrap: {
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    margin: 0,
    paddingTop: 0,
  },
  bottomText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomMediumFont,
    color: colors.PrimaryTextColor,
    marginBottom: Dimension.margin10,
  },
  couponModalInner: {
    // width: Dimension.SCREEN_WIDTH,
    // position: 'absolute',
    flex: 1,
    bottom: 0,
    top: 0,
    left: 0,
    backgroundColor: colors.brandbg,
    flex: 1,
  },
  couponModalHeaderFlex: {
    flexDirection: 'row',
    paddingHorizontal: Dimension.padding15,
    paddingVertical: Dimension.padding12,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  couponModalHeading: {
    marginLeft: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font14,
    paddingTop: 2,
    color: colors.PrimaryTextColor,
  },
  moglixlogo: {
    alignSelf: 'center',
    width: Dimension.width100,
    height: Dimension.height50,
    marginBottom: Dimension.margin15,
  },
  couponScrollViewWrap: {
    paddingHorizontal: Dimension.padding20,
    paddingTop: 0,
    paddingBottom: Dimension.padding20,
  },
  offerMediumText: {
    fontFamily: Dimension.CustomMediumFont,
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font16,
  },
  offerBoldText: {
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font14,
  },
  offerBottomText: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomMediumFont,
    marginBottom: 15,
  },
  submitButton: {
    height: Dimension.height34,
    backgroundColor: colors.RedThemeColor,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: Dimension.borderRadius4,
  },
  submitButtonText: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: '#fff',
  },
  submitButtonDisabled: {
    backgroundColor: colors.ExtralightGrayText,
    height: Dimension.height34,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: Dimension.borderRadius4,
  },
  // How it works MODAL
  hiwModalWrap: {
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    margin: 0,
    paddingTop: 0,
  },
  hiwModalInner: {
    width: Dimension.SCREEN_WIDTH,
    position: 'absolute',
    bottom: 0,
    top: 0,
    left: 0,
    backgroundColor: '#fff',
    flex: 1,
  },
  hiwModalHeaderFlex: {
    flexDirection: 'row',
    paddingHorizontal: Dimension.padding15,
    paddingVertical: Dimension.padding12,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  hiwModalHeading: {
    // marginLeft: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font14,
    paddingTop: 2,
    color: colors.PrimaryTextColor,
  },
  hiwScrollViewWrap: {
    paddingHorizontal: Dimension.padding15,
    paddingTop: 0,
    paddingBottom: Dimension.padding20,
  },
  hiwIndexRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    shadowColor: '#000',
    paddingVertical: Dimension.padding5,
    paddingHorizontal: Dimension.padding10,
    flex: 1,
    shadowOffset: {width: 0, height: 1},
    marginBottom: Dimension.margin10,
    borderWidth: 1,
    borderColor: '#fafafa',
    borderRadius: Dimension.borderRadius4,
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
    alignItems: 'center',
  },
  hiwLeftText: {flexDirection: 'row', alignItems: 'center', flex: 2},
  hiwIndex: {
    color: colors.BoldgreenText,
    fontSize: Dimension.font26,
    fontFamily: Dimension.CustomBoldFont,
  },
  hiwIndexContent: {
    fontSize: Dimension.font12,
    paddingLeft: Dimension.padding10,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
    justifyContent: 'center',
    width: '85%',
  },
  emistep: {
    width: '100%',
    height: Dimension.height200,
    marginBottom: Dimension.margin20,
  },
  // variantTitle:{marginBottom:-Dimension.margin10},
  fbtModalByATC: {
    margin: 0,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
});

export default styles;
