import {StyleSheet} from 'react-native';
import colors from '../../../redux/constants/colors';
import Dimension from '../../../redux/constants/dimensions';

const styles = StyleSheet.create({
  mainAuthScreenView: {
    backgroundColor: colors.RedThemeColor,
    flex: 1,
    padding: Dimension.padding15,
  },
  signInRedScreen: {
    backgroundColor: colors.RedThemeColor,
    flex: 1,
    // justifyContent: 'flex-end',
    marginTop:Dimension.margin30
  },
  backHeader: {
    backgroundColor: 'transparent',
    shadowColor: 'transparent',
    padding: 0,
    paddingHorizontal: 0,
  },
  iconColor: {color: colors.white},
  title: {
    fontSize: Dimension.font16,
    color: colors.white,
    fontFamily: Dimension.CustomBoldFont,
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: Dimension.font12,
    color: colors.white,
    marginBottom: Dimension.margin10,
    fontFamily: Dimension.CustomRegularFont,
  },
  whiteBg: {
    backgroundColor: colors.white,
    padding: Dimension.padding15,
    borderRadius: Dimension.borderRadius12,
    marginBottom: Dimension.margin15,
  },
  inputWrap: {flexDirection: 'row', justifyContent: 'space-between',
alignItems:'flex-start',alignSelf:"flex-start"
},
  invisibleTextInput: {width: 0, height: 0, opacity: 0,
    marginLeft:0,
    paddingLeft:0,
    marginHorizontal:0,
    paddingHorizontal:0, 
  },
  textInputStyle: {
    borderWidth: 1,
    width: '14%',
    color: colors.PrimaryTextColor,
    paddingVertical: Dimension.padding12,
    paddingHorizontal: Dimension.padding5,
    textAlign: 'center',
    fontSize: Dimension.font14,
    borderColor: colors.ExtralightGrayText,
    borderRadius: Dimension.borderRadius8,
    shadowColor: '#333',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0,
    shadowRadius: 1,
    elevation: 8,
    backgroundColor: colors.white,
    marginRight:Dimension.margin8,

  },
  codeReciveWrap: {
    flexDirection: 'row',
    marginBottom: Dimension.margin5,
   
    paddingTop: Dimension.padding20,
  },
  resendOTP: {marginLeft: 'auto'},
  codeResend: {
    fontSize: Dimension.font10,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  resendotptext: {
    color: colors.RedThemeColor,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginTop: Dimension.margin5,
  },
  orView: {
    width: '100%',
    height: 1,
    position: 'relative',
    backgroundColor: colors.ProductBorderColor,
    marginVertical: Dimension.margin20,
    alignItems: 'center',
  },
  orText: {
    color: '#343434',
    position: 'absolute',
    backgroundColor: colors.white,
    fontSize: Dimension.font11,
    fontFamily: Dimension.CustomRegularFont,
    paddingHorizontal: Dimension.padding10,
    top: -8,
  },
  BtnText: {
    alignSelf: 'center',
    color: colors.white,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomBoldFont,
  },
  contBtn: {
    height: Dimension.height40,
    width: '100%',
    backgroundColor: colors.PrimaryTextColor,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Dimension.borderRadius8,
    marginTop: 0,
  },
  errorText: {
    color: colors.RedThemeColor,
    fontSize: Dimension.font11,
    marginTop: Dimension.margin5,
  },
  validText: {
    color: colors.green2,
    fontSize: Dimension.font11,
    marginTop: Dimension.margin5,
  },
  textInputwithErrorStyle: {
    borderWidth: 1,
    width: '14%',
    color: colors.PrimaryTextColor,
    paddingHorizontal: Dimension.padding5,
    textAlign: 'center',
    fontSize: Dimension.font14,
    borderColor: colors.RedThemeColor,
    borderRadius: Dimension.borderRadius8,
    shadowColor: '#333',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0,
    shadowRadius: 1,
    elevation: 8,
    backgroundColor: colors.white,
    paddingVertical: Dimension.padding12,marginRight:Dimension.margin8,

  },
  textInputwithVerifiedStyle: {
    borderWidth: 1,
    width: '14%',
    color: colors.PrimaryTextColor,
    paddingHorizontal: Dimension.padding5,
    textAlign: 'center',
    fontSize: Dimension.font14,
    borderColor: colors.green2,
    borderRadius: Dimension.borderRadius8,
    shadowColor: '#333',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0,
    shadowRadius: 1,
    elevation: 8,
    backgroundColor: colors.white,
    paddingVertical: Dimension.padding12,marginRight:Dimension.margin8,

  },
  blueLink: {
    paddingTop: Dimension.padding15,
    alignItems: 'center',
    paddingBottom: Dimension.padding5,
  },
  linkText: {
    fontSize: Dimension.font12,
    color: colors.BlueText,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  redBtn: {
    height: Dimension.height40,
    width: '100%',
    backgroundColor: colors.RedThemeColor,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: Dimension.borderRadius8,
    marginTop: Dimension.margin20,
  },
  disableBtn: {
    height: Dimension.height40,
    width: '100%',
    backgroundColor: colors.ExtralightGrayText,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: Dimension.borderRadius8,
    marginTop: Dimension.margin20,
  },
  rbsSubTitle: {
    fontSize: Dimension.font4, 
    color: colors.lightGrayText
  },
  passIcon: {position: 'absolute', right: 10, top: 9,},
  disableInput: {borderColor: 'rgba(69, 79, 99, 0.3)'},
  labelDisable: {color: 'rgba(69, 79, 99, 0.3)'},
});

export default styles;
