import {StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import Colors from '../../redux/constants/colors';
import colors from '../../redux/constants/colors';

const styles = StyleSheet.create({
  voiceIconCss: {
    color: Colors.BlueText,
    fontSize: Dimension.font22,
    // position: 'absolute',
    // right: Dimension.margin12,
    // top: Dimension.margin10,
  },
  searcinputText: {
    fontSize: Dimension.font12,
    marginLeft: Dimension.margin15,
    fontFamily: Dimension.CustomRegularFont,
    color: Colors.lightGrayText,
    textAlignVertical: 'center',
    // borderRadius: 8,
    backgroundColor: '#fff',
    // justifyContent: 'center',
    // borderWidth: 1,
    // borderColor: '#C9C9C9',
    // width: '100%',
    // flex: 1,
    // position: 'relative',
    // paddingLeft: Dimension.padding40,
    // height: Dimension.height40,
  },
  searcinputTextBold: {
    fontSize: Dimension.font12,
    color: Colors.lightGrayText,
    textAlignVertical: 'center',
    borderRadius: 8,
    backgroundColor: '#fff',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C9C9C9',
    width: '100%',
    flex: 1,
    position: 'relative',
    paddingLeft: Dimension.padding40,
    height: Dimension.height40,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  searchIconWrap: {
    // position: 'absolute',
    // left: Dimension.margin20,
    // top: Dimension.margin12,
  },
  SearchIcon: {
    width: Dimension.height24,
    height: Dimension.width24,
    tintColor: Colors.PrimaryTextColor,
  },
  signInSuggestionText: {
    color: Colors.lightGrayText,
    fontFamily: Dimension.CustomRegularFont,
    fontSize: Dimension.font10,
    marginTop: Dimension.margin8,
    alignSelf: 'center',
  },
  ProfileTop: {
    // marginTop: Dimension.margin12,
    backgroundColor: '#fff',
    padding: Dimension.padding14,
    flex: 1,
  },
  redCard: {
    backgroundColor: Colors.RedThemeColor,
    borderRadius: 8,
    padding: Dimension.padding14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  redCardText: {
    color: Colors.white,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font14,
    // fontWeight: 'bold',
  },
  searchView:{
    paddingVertical: Dimension.margin10,
    backgroundColor: '#fff',
    margin: 12,
    paddingHorizontal: Dimension.padding12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 8,
    borderColor: '#C9C9C9',
    borderWidth: 1,
    alignItems: 'center',
  },
  searchViewInner:{
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerView:{
    backgroundColor: '#fff',
    borderBottomColor: '#C9C9C9',
    borderBottomWidth: 0.5,
  },
  pageView:{
    backgroundColor: '#F7F7FA',
    flex: 1,
  },
  profileTabs:{
    paddingHorizontal: 14,
    marginTop: Dimension.margin20,
    marginHorizontal: 20,
    borderRadius: 12,
    borderColor: '#e7e7e7',
    borderWidth: 0.5,
    backgroundColor: '#fff',
    bottom:10
  },
  profileClick:{flex: 1,
    flexDirection: 'row',
    paddingVertical: Dimension.padding12,
    alignItems: 'center',
    borderBottomColor: '#e7e7e7'},
  profileText:{
    fontSize: Dimension.font12,
    marginLeft: Dimension.padding15,
    fontFamily:Dimension.CustomRegularFont
  },
  redStrip:{backgroundColor:colors.RedThemeColor,borderRadius:8,padding:Dimension.padding15,flexDirection:"row"},
  accountView:{padding:Dimension.padding15,backgroundColor:'#fff', paddingVertical:Dimension.padding15},
  userDetail:{marginLeft:Dimension.margin15, flex:2},
  userIconWrap:{backgroundColor:"#F7F7FA",borderRadius:Dimension.borderRadius10,width:Dimension.width70,height:Dimension.width70,justifyContent:"center",alignItems:"center"},
  UserIconImg:{width:Dimension.width65,height:Dimension.width65},
  nameCol:{flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom:Dimension.margin10},
  userName:{color:'#fff',fontFamily:Dimension.CustomSemiBoldFont,fontSize:Dimension.font14},
  usrDet:{flexDirection:'row', alignItems:'center',marginBottom:Dimension.margin10},
  usrDetText:{color:"rgba(255,255,255,.80)",fontFamily:Dimension.CustomRegularFont,fontSize:Dimension.font12,marginLeft:Dimension.margin10},
  noterow:{flexDirection: 'row',alignItems:'center', justifyContent:'space-between', paddingVertical:Dimension.padding10},
  noteText:{width:'65%', paddingRight:Dimension.padding15,color: Colors.lightGrayText,
  fontFamily: Dimension.CustomRegularFont,
  fontSize: Dimension.font11,},
  verifyBtn:{ backgroundColor:colors.LightRedThemeColor,paddingHorizontal:Dimension.padding15,borderRadius:4,height:Dimension.width26,justifyContent:"center",alignItems:'center'},
  verifyBtnText:{color:colors.RedThemeColor,fontFamily:Dimension.CustomSemiBoldFont,fontSize:Dimension.font12,},
  noteHading: {
    color: Colors.PrimaryTextColor,
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font11,
  },
  profileBlockWrap:{flexDirection:'row',alignItems:'center',paddingVertical:Dimension.padding10,borderColor:colors.ProductBorderColor, borderWidth:1, backgroundColor:'#fff', borderRadius:Dimension.borderRadius8,marginBottom:Dimension.margin15,paddingHorizontal:Dimension.padding10, marginTop:Dimension.padding15},
  profileActText:{color:colors.PrimaryTextColor, fontSize:Dimension.font12, marginLeft:Dimension.margin15, fontFamily:Dimension.CustomMediumFont},
  logoutView:{paddingHorizontal:Dimension.padding15}
});

export default styles;
