import {StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import Colors from '../../redux/constants/colors';
import colors from '../../redux/constants/colors';

const styles = StyleSheet.create({
  homeLoginBg: {
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: Dimension.borderRadius8,
    borderTopRightRadius: Dimension.borderRadius8,
    backgroundColor: 'rgba(247,247,247,0.97)',
    width: '100%',
  },
  textCenter: {alignSelf: 'center'},
  carouselContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: Dimension.padding5,
    paddingBottom: Dimension.padding10,
    position: 'relative',
  },
  magnifyIcon: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font22,
    // position: 'absolute',
    // right: Dimension.margin12,
    // top: Dimension.margin10,
  },
  voiceIconCss: {
    color: Colors.BlueText,
    fontSize: Dimension.font22,
    // position: 'absolute',
    // right: Dimension.margin12,
    // top: Dimension.margin10,
  },
  searcinputText: {
    fontSize: Dimension.font12,
    marginLeft: Dimension.margin15,
    fontFamily: Dimension.CustomRegularFont,
    color: Colors.lightGrayText,
    textAlignVertical: 'center',
    // borderRadius: 8,
    backgroundColor: '#fff',
    // justifyContent: 'center',
    // borderWidth: 1,
    // borderColor: '#C9C9C9',
    // width: '100%',
    // flex: 1,
    // position: 'relative',
    // paddingLeft: Dimension.padding40,
    // height: Dimension.height40,
  },
  serachWarpView:{
    width:'87%',
    height:'70%',
    flexDirection:'row',
   },
   iconView:{
    width:20,
   },
  searcinputTextBold: {
    fontSize: Dimension.font12,
    color: Colors.lightGrayText,
    textAlignVertical: 'center',
    borderRadius: 8,
    backgroundColor: '#fff',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C9C9C9',
    width: '100%',
    flex: 1,
    position: 'relative',
    paddingLeft: Dimension.padding40,
    height: Dimension.height40,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  searchIconWrap: {
    // position: 'absolute',
    // left: Dimension.margin20,
    // top: Dimension.margin12,
  },
  SearchIcon: {
    width: Dimension.height24,
    height: Dimension.width24,
    tintColor: Colors.PrimaryTextColor,
  },
  sectionTitle: {paddingHorizontal: Dimension.padding15},
  searchBar: {
    paddingVertical: Dimension.margin10,
    backgroundColor: '#fff',
    marginHorizontal: Dimension.margin12,
    marginVertical:Dimension.margin10,
    paddingHorizontal: Dimension.padding12,
    paddingRight:Dimension.padding15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: Dimension.borderRadius8,
    borderColor: '#C9C9C9',
    borderWidth: 1,
    alignItems: 'center',
  },
  searchBarInner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  activityIndicator: {
    alignSelf: 'center',
  },
  topHeaderCategory: {
    width: '100%',
    paddingVertical: Dimension.padding10,
    backgroundColor: '#fff',
  },
  exploreBrands: {
    paddingBottom: Dimension.margin12,
  },
  brandView: {
    marginTop: Dimension.margin10,
    paddingBottom: Dimension.padding10,
  },
  bestSellerView: {
    paddingBottom: Dimension.margin12,
    paddingTop: Dimension.padding10,
  },
  searchHeader: {
    backgroundColor: '#fff',
    // borderBottomColor: '#C9C9C9',
    // borderBottomWidth: 0.5,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.20,
    shadowRadius: 1.41,
    elevation: 2,
  },
  homeOfficeBrands: {paddingBottom: Dimension.margin12},
  homeOfficeBrandsInner: {
    paddingHorizontal: Dimension.padding15,
    paddingTop: Dimension.padding15,
  },
  spotLight: {
    paddingTop: Dimension.margin10,
  },
  spotLightView: {paddingHorizontal: Dimension.padding15},
  searchBox: {
    paddingVertical: Dimension.margin10,
    backgroundColor: '#fff',
    margin: 12,
    paddingHorizontal: Dimension.padding12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 8,
    borderColor: '#C9C9C9',
    borderWidth: 1,
    alignItems: 'center',
  },
  searchBoxInner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  allbrandsView: {
    flexDirection: 'column',
  },
  error: {alignSelf: 'center'},
  searchHeaderView: {
    backgroundColor: '#fff',
    borderBottomColor: '#C9C9C9',
    borderBottomWidth: 0.5,
  },
  brandStoreView: {flex: 1},
  // Header Style
  homeHeader: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    paddingHorizontal: Dimension.padding15,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: Dimension.padding10,
  },
  moglixlogo: {width: Dimension.width45},
  welcomeUser: {
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font12,
    width: Dimension.width105,
    color: colors.PrimaryTextColor,
  },
  cartWrap: {position: 'relative'},
  shoppingCart: {},
  cartItemCount: {
    backgroundColor: colors.RedThemeColor,
    borderRadius: Dimension.borderRadius4,
    paddingVertical: Dimension.padding2,
    color: '#fff',
    fontSize: Dimension.font11,
    fontFamily: Dimension.CustomMediumFont,
    position: 'absolute',
    justifyContent: 'center',
    textAlign: 'center',
    alignContent: 'center',
    paddingHorizontal: Dimension.padding5,
    right: -5,
    top: -10,
  },
  headerWithoutshadow:{shadowOpacity:0,shadowRadius:0,elevation:0,paddingBottom:0},
  VertProductListSection:{
    paddingLeft:Dimension.padding5, 
    marginBottom:-Dimension.margin5,
  }
});

export default styles;
