import {Dimensions, StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import Colors from '../../redux/constants/colors';
import colors from '../../redux/constants/colors';

const styles = StyleSheet.create({
  cardView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    // marginBottom: Dimension.margin15,
    // borderColor: '#EFEFF4',
    // borderWidth: 1,
    overflow: 'hidden',
    paddingVertical: Dimension.padding12,
  },
  BtnText: {
    alignSelf: 'center',
    color: '#fff',
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomBoldFont,
  },
  redBtn: {
    flexDirection: 'row',
    height: Dimension.height40,
    width: '100%',
    backgroundColor: colors.RedThemeColor,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Dimension.borderRadius8,
    marginTop: Dimension.margin20,
  },
  activityIndicator: {
    backgroundColor: '#e7e7e7',
    // borderRadius: 8,
    // width: '100%',
    // marginHorizontal: 12,
    // marginBottom: 8,
    // justifyContent:'center',
    // alignSelf: 'center',
    height: 600,
  },
  orderWrap: {
    backgroundColor: '#fff',
    paddingHorizontal: Dimension.padding15,
    marginBottom: Dimension.margin10,
  },
  myOrderHead: {
    margin: Dimension.margin15,
  },
  myOrderTxt: {
    color: colors.LightTextColor,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  orderSearchWrap: {
    flexDirection: 'row',
    backgroundColor: '#F7F7FA',
    paddingVertical: Dimension.padding10,
    borderBottomColor: colors.accborder,
    borderBottomWidth: 1,
    paddingHorizontal: Dimension.padding15,
    justifyContent: 'space-between',
  },
  LogoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: Dimensions.get('window').width * 0.67,
    borderWidth: 1,
    paddingLeft: Dimension.padding10,
    borderRadius: Dimension.borderRadius8,
    borderColor: '#C9C9C9',
    height: Dimension.height34,
    backgroundColor: '#fff',
  },
  searchText: {
    marginLeft: Dimension.margin6,
    fontSize: Dimension.font12,
    width: '82%',
    fontFamily: Dimension.CustomRegularFont,
    alignItems: 'center',
    marginTop: Dimension.margin5,
    color: '#000',
    paddingVertical: Dimension.padding5,
  },
  listWrapInner: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterIcon: {fontSize: Dimension.font24},
  listHeaderText: {
    marginLeft: Dimension.padding8,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomMediumFont,
    color: Colors.PrimaryTextColor,
    lineHeight: Dimension.width24,
    justifyContent: 'center',
  },
  filterCountWrap: {
    paddingHorizontal: Dimension.padding6,
    borderRadius: 3,
    backgroundColor: colors.LightRedThemeColor,
    height: Dimension.height14,
    // width: Dimension.width14,
    justifyContent: 'center',
    marginLeft: Dimension.margin5,
    // marginTop: Dimension.margin6,
  },
  filterCountText: {
    fontSize: Dimension.font10,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.RedThemeColor,
    justifyContent: 'center',
  },
  noOrders: {
    paddingHorizontal: Dimension.padding15,
    marginTop: Dimension.margin15,
  },
  whiteBgWithImage: {
    backgroundColor: '#fff',
    padding: Dimension.padding15,
    paddingHorizontal: Dimension.padding30,
    alignItems: 'center',
    paddingTop: Dimension.padding50,
    paddingBottom: Dimension.padding30,
    borderRadius: Dimension.borderRadius16,
  },
  noOrderImage: {width: Dimension.width185, height: Dimension.width150},
  noOrderText: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomMediumFont,
    color: colors.PrimaryTextColor,
    marginTop: Dimension.margin30,
  },
  noOrderContent: {
    color: colors.lightGrayText,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomRegularFont,
    textAlign: 'center',
    marginTop: Dimension.margin20,
  },
  orderNumText: {
    fontFamily: Dimension.CustomMediumFont,
    color: colors.lightGrayText,
    fontSize: Dimension.font12,
  },
  prodName: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
  },
  footerCardItem: {
    flex: 1,
    borderTopColor: Colors.ProductBorderColor,
    borderTopWidth: 1,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    paddingTop: Dimension.padding10,
    paddingBottom: Dimension.padding10,
    paddingRight: Dimension.padding10,
    paddingLeft: Dimension.padding10,
  },
  dot: {
    width: Dimension.width10,
    height: Dimension.width10,
    borderRadius: Dimension.borderRadius30,
    marginRight: Dimension.margin10,
  },
  reddot: {backgroundColor: Colors.RedThemeColor},
  greendot: {backgroundColor: Colors.BoldgreenText},
  orangedot: {backgroundColor: Colors.orangeShade},
  buyagain: {
    paddingHorizontal: Dimension.padding15,
    height: Dimension.height27,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.LightRedThemeColor,
    borderRadius: Dimension.borderRadius4,
    flexDirection: 'row',
  },
  buyagaintext: {
    fontSize: Dimension.font12,
    color: colors.RedThemeColor,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  prodCard: {
    borderWidth: 1,
    borderColor: colors.ProductBorderColor,
    marginBottom: Dimension.margin10,
    borderRadius: Dimension.borderRadius8,
  },
  prodDetailWrap: {
    padding: Dimension.padding10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  leftImageIcon: {width: Dimension.width74, height: Dimension.width74},
  prodDetail: {paddingLeft: Dimension.padding15, flex: 1},
  priceqty: {
    flexDirection: 'row',
    paddingTop: Dimension.padding10,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  price: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomRobotoBold,
    color: colors.PrimaryTextColor,
  },
  qty: {
    fontSize: Dimension.font12,
    marginTop: 3,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomRegularFont,
  },
  priceCol: {flexDirection: 'row'},
  footerCardItem: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: colors.ProductBorderColor,
    justifyContent: 'space-between',
    padding: Dimension.padding10,
  },
  orderStatus: {
    fontSize: Dimension.font11,
    color: colors.PrimaryTextColor,
    // width:Dimension.width40,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  date: {
    fontSize: Dimension.font11,
    marginTop: -2,
    color: colors.lightGrayText,
    fontFamily: Dimension.CustomRegularFont,
  },
  progressBar: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    flexBasis: '40%',
  },
  dot: {
    width: Dimension.width10,
    height: Dimension.width10,
    borderWidth: 1,
    borderColor: colors.ProductBorderColor,
    borderRadius: Dimension.borderRadius30,
  },
  greenDot: {
    width: Dimension.width10,
    height: Dimension.width10,
    borderWidth: 1,
    borderColor: colors.BoldgreenText,
    borderRadius: Dimension.borderRadius30,
    backgroundColor: colors.BoldgreenText,
  },
  orderDate: {
    flexBasis: '20%',
  },
  wrapView: {
    // backgroundColor:'red',
    width: Dimension.width100,
  },
  wrapView1: {
    // backgroundColor:'red',
    width: Dimension.width90,
  },
  etDate: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    flexBasis: '20%',
  },
  orderViewWrap: {
    paddingBottom: Dimension.height90,
  },
  progressLine: {
    width: '100%',
    flex: 1,
    height: Dimension.margin3,
    backgroundColor: colors.ProductBorderColor,
  },
  progressGreenLine: {
    height: Dimension.margin3,
    backgroundColor: colors.BoldgreenText,
  },
});

export default styles;
