import {Dimensions, StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import colors from '../../redux/constants/colors';

const styles = StyleSheet.create({
  voiceIconCss: {
    color: colors.BlueText,
    fontSize: Dimension.font22,
    // position: 'absolute',
    // right: Dimension.margin12,
    // top: Dimension.margin10,
  },
  searcinputText: {
    fontSize: Dimension.font12,
    marginLeft: Dimension.margin15,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.lightGrayText,
    textAlignVertical: 'center',
    backgroundColor: '#fff',
  },
  cattext: {
    fontSize: Dimension.font12,
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius8,
    justifyContent: 'center',
    fontFamily: Dimension.CustomMediumFont,
    marginRight: Dimension.margin10,
    color: colors.PrimaryTextColor,
    paddingHorizontal: Dimension.padding10,
    paddingVertical: Dimension.padding5,
    borderWidth: 1,
    borderColor: '#EFEFF4',
  },
  recommHeading: {
    fontFamily: Dimension.CustomBoldFont,
    marginBottom: Dimension.margin8,
    color: colors.PrimaryTextColor,
  },

  BuyNowBtn: {
    height: Dimension.height40,
    margin: Dimension.margin6,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.RedThemeColor,
    flexDirection: 'row',
    borderRadius: Dimension.borderRadius8,
  },
  BuyNowBtnText: {
    color: colors.white,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomBoldFont,
  },
  videoWrap: {
    marginTop: Dimension.margin14,
    backgroundColor: '#fff',
    borderTopLeftRadius: Dimension.borderRadius8,
    borderTopRightRadius: Dimension.borderRadius8,
    borderBottomLeftRadius: Dimension.borderRadius8,
    borderBottomRightRadius: Dimension.borderRadius8,
    overflow: 'hidden',
    position: 'relative',
    alignItems: 'center',
    borderWidth: 0.7,
    borderColor: '#EFEFF4',
    marginBottom: -Dimension.margin20,
    zIndex: 9,
    paddingVertical: 12,
  },
  youtubeWrap: {width: '94%', alignSelf: 'center', overflow: 'hidden'},
  videoTitle: {
    marginVertical: Dimension.margin8,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
  },

  cartBtnText: {
    fontSize: Dimension.font11,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: '#fff',
  },
  listViewCard: {
    position: 'relative',
    marginTop: -Dimension.margin12,
  },
  listCardBtns: {
    position: 'absolute',
    right: Dimension.margin25,
    top: Dimension.height70,
    zIndex: 1,
  },
  cartBtn: {
    // position: 'absolute',
    zIndex: 2,
    width: Dimension.width80,
    backgroundColor: colors.RedThemeColor,
    height: Dimension.height24,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Dimension.padding15,
    borderRadius: Dimension.borderRadius4,
  },
  sendQueryBtn: {
    // position: 'absolute',
    zIndex: 2,
    width: Dimension.width80,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: colors.RedThemeColor,
    height: Dimension.height27,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Dimension.padding15,
    borderRadius: Dimension.borderRadius4,
  },
  sendQueryBtnText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.RedThemeColor,
  },
  searcinputTextBold: {
    fontSize: Dimension.font12,
    color: colors.lightGrayText,
    textAlignVertical: 'center',
    borderRadius: 8,
    backgroundColor: '#fff',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C9C9C9',
    width: '100%',
    flex: 1,
    position: 'relative',
    paddingLeft: Dimension.padding40,
    height: Dimension.height40,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  searchIconWrap: {},
  SearchIcon: {
    width: Dimension.height24,
    height: Dimension.width24,
    tintColor: colors.PrimaryTextColor,
  },
  cardView: {
    flex: 1,
    backgroundColor: 'white',
    marginHorizontal: Dimension.margin15,
    marginBottom: Dimension.margin15,
    borderRadius: Dimension.borderRadius8,
    borderColor: '#EFEFF4',
    borderWidth: 1,
    overflow: 'hidden',
    // flexDirection:'row',
    padding: Dimension.padding12,
    // shadowColor: '#000',
    // shadowOffset: {width: 0.5, height: 0.5},
    // shadowOpacity: 0.5,
    // shadowRadius: 3,
    // elevation: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  ModalContentWrap: {
    paddingRight: 0,
    paddingBottom: 0,
    paddingTop: 0,
    paddingLeft: 0,
    backgroundColor: colors.PrimaryTextColor,
  },
  signUpWrap: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingTop: Dimension.padding15,
  },
  SoryByData: {
    borderTopColor: colors.ProductBorderColor,
    flexDirection: 'row',
    padding: Dimension.padding15,
    borderTopWidth: 1,
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  radioWrap: {marginTop: Dimension.margin5},
  sortBtdata: {
    alignSelf: 'center',
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomMediumFont,
    color: colors.PrimaryTextColor,
    marginLeft: Dimension.margin20,
  },
  exploreWrapper: {
    backgroundColor: colors.ExtralightGrayText,
    paddingHorizontal: Dimension.padding15,
    paddingTop: Dimension.padding10,
    paddingBottom: Dimension.padding12,
    marginTop: Dimension.margin5,
    marginBottom: Dimension.margin10,
  },
  exploreText: {
    fontSize: Dimension.font14,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginBottom: Dimension.margin8,
  },
  exploreBrandCard: {
    borderWidth: 2,
    borderColor: colors.ProductBorderColor,
    elevation: 0,
    padding: Dimension.padding8,
    borderRadius: 8,
  },
  exploreBrandTextContainer: {
    paddingLeft: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 0,
    position: 'relative',
    marginBottom: 0,
  },
  exploreBrandText: {
    fontSize: Dimension.font14,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomRobotoRegular,
  },
  searchView: {
    paddingVertical: Dimension.margin10,
    backgroundColor: '#fff',
    margin: 12,
    paddingHorizontal: Dimension.padding12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 8,
    borderColor: '#C9C9C9',
    borderWidth: 1,
    alignItems: 'center',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  prodName: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  catChildItem: {
    marginLeft: Dimension.margin12,
    color: '#000',
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  activityIndicator: {
    // backgroundColor: '#e7e7e7',
    // borderRadius: 8,
    // width: '100%',
    // marginHorizontal: 12,
    // marginBottom: 8,
    // paddingVertical: 50,
    height: '90%',
    alignSelf: 'center',
  },
  mainHeader: {
    backgroundColor: '#fff',
    borderBottomColor: '#C9C9C9',
    borderBottomWidth: 0.5,
  },
  catChildCard: {
    backgroundColor: 'white',
    marginRight: Dimension.margin10,
    marginBottom: Dimension.margin10,
    height: Dimension.height40,
    paddingHorizontal: Dimension.padding10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: Dimension.borderRadius8,
    borderWidth: 1,
    borderColor: colors.ProductBorderColor,
  },
  flatListRow: {
    paddingHorizontal: Dimension.padding15,
    paddingTop: Dimension.padding5,
    height: Dimension.height50,

    // overflow: 'hidden',
    backgroundColor: '#fff',
    // position: 'relative',
    // zIndex: 2,
  },
  brands: {
    marginRight: Dimension.margin10,
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius8,
    paddingHorizontal: Dimension.padding10,
    paddingVertical: Dimension.padding8,
  },
  listingHeader: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    paddingTop: Dimension.padding12,
    paddingBottom: Dimension.padding5,
    paddingHorizontal: Dimension.padding15,
    position: 'relative',
    textTransform: 'capitalize',
  },
  filterHeadRow: {
    position: 'relative',
    zIndex: 1,
  },
  greyText: {
    color: colors.lightGrayText,
    fontFamily: Dimension.CustomRegularFont,
  },
  leftProdImage: {
    width: Dimension.prdListViewImage,
    height: Dimension.prdListViewImage,
  },
  rightArea: {
    paddingLeft: Dimension.padding15,
    position: 'relative',
    width: '75%',
  },
  rateProd: {flexDirection: 'row', marginBottom: Dimension.margin5},
  prodRating: {
    flexDirection: 'row',
    backgroundColor: colors.ratingColor,
    borderRadius: Dimension.borderRadius4,
    paddingHorizontal: Dimension.padding6,
    height: 20,
    alignItems: 'center',
  },
  ratingCount: {
    color: '#fff',
    fontSize: Dimension.font11,
    marginTop: -2,
    fontFamily: Dimension.CustomRobotoBold,
  },
  starIcon: {color: '#fff', fontSize: Dimension.font8, marginLeft: 3},
  reviewCount: {
    marginLeft: 5,
    color: colors.ExtralightGrayText,
    fontSize: Dimension.font11,
    alignSelf: 'center',
  },
  wishlist: {position: 'absolute', right: 0, top: -5},
  prodAreaTop: {flexDirection: 'row', flex: 1},
  wishlistIcon: {fontSize: Dimension.font18, color: colors.ExtralightGrayText},
  wishlistIconActive: {fontSize: Dimension.font18, color: colors.RedThemeColor},
  bybrand: {
    color: '#C9C9C9',
    fontSize: Dimension.font11,
    marginBottom: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  percentOff: {flexDirection: 'row', alignItems: 'center', marginBottom: -5},
  offPrice: {
    fontSize: Dimension.font11,
    color: 'rgba(43, 43, 43, 0.5)',
    fontFamily: Dimension.CustomRobotoRegular,
    marginTop: -4,
    textDecorationLine: 'line-through',
  },
  greenText: {
    fontSize: Dimension.font12,
    color: colors.ratingColor,
    fontFamily: Dimension.CustomBoldFont,
    paddingLeft: Dimension.padding10,
  },
  price: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mainPrice: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomRobotoBold,
    color: colors.PrimaryTextColor,
  },
  qty: {
    fontSize: Dimension.font10,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomRegularFont,
  },
  addToCartBtn: {
    paddingHorizontal: Dimension.padding15,
    backgroundColor: colors.RedThemeColor,
    paddingVertical: Dimension.padding8,
    borderRadius: Dimension.borderRadius4,
  },
  addToCartText: {
    fontSize: Dimension.font12,
    color: '#fff',
    fontFamily: Dimension.CustomRobotoBold,
  },
  availRequest: {
    fontSize: Dimension.font10,
    fontFamily: Dimension.CustomBoldFont,
    color: colors.PrimaryTextColor,
  },
  // sendQueryBtn: {
  //   paddingHorizontal: Dimension.padding15,
  //   borderWidth: 1,
  //   borderColor: colors.RedThemeColor,
  //   paddingVertical: Dimension.padding8,
  //   borderRadius: Dimension.borderRadius4,
  // },
  sendQueryText: {
    fontSize: Dimension.font12,
    color: colors.RedThemeColor,
    fontFamily: Dimension.CustomRobotoBold,
  },
  feature: {flexDirection: 'row', marginVertical: Dimension.margin10},
  featureType: {
    paddingTop: Dimension.padding4,
    paddingBottom: Dimension.padding2,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.ProductBorderColor,
    borderRadius: Dimension.borderRadius4,
    marginRight: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font10,
    color: colors.ExtralightGrayText,
    paddingHorizontal: Dimension.padding5,
  },
  flist: {flexDirection: 'row', marginBottom: 7},
  greydot: {
    width: Dimension.width8,
    height: Dimension.width8,
    borderRadius: Dimension.borderRadius16,
    backgroundColor: colors.ExtralightGrayText,
    marginRight: 10,
    marginTop: 4,
  },
  listText: {
    fontSize: Dimension.font11,
    lineHeight: Dimension.height16,
    color: colors.lightGrayText,
    fontFamily: Dimension.CustomMediumFont,
  },
  noOrders: {paddingHorizontal: Dimension.padding15},
  whiteBgWithImage: {
    backgroundColor: '#fff',
    padding: Dimension.padding15,
    alignItems: 'center',
    paddingBottom: Dimension.padding30,
    borderRadius: Dimension.borderRadius16,
  },
  noOrderImage: {width: Dimension.width150, height: Dimension.width120},
  noOrderText: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    marginTop: Dimension.margin10,
    marginBottom: Dimension.margin30,
  },
  noOrderContent: {
    color: colors.LightTextColor,
    fontSize: Dimension.font14,
    paddingHorizontal: Dimension.padding15,
    fontFamily: Dimension.CustomRegularFont,
    textAlign: 'center',
    marginTop: Dimension.margin20,
  },
  noboxshadow: {shadowOpacity: 0, shadowRadius: 0, elevation: 0},
  // listingArea:{paddingLeft:Dimension.padding15},
  listingWidth: {
    maxWidth: Dimensions.get('window').width,
    marginLeft: Dimension.margin15,
  },
});

export default styles;
