export const ADDRESS_ACTIONS = {
  FETCH_ADDRESS_BY_INVOICETYPE: 'FETCH_ADDRESS_BY_INVOICETYPE',
  FETCHED_ADDRESS_BY_INVOICETYPE: 'FETCHED_ADDRESS_BY_INVOICETYPE',
  FAILED_FETCH_ADDRESS_BY_INVOICETYPE: 'FAILED_FETCH_ADDRESS_BY_INVOICETYPE',
  SET_BILLING_ADDRESS: 'SET_BILLING_ADDRESS',
  SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',

  UPDATE_ADDRESS_BY_INVOICETYPE: 'UPDATE_ADDRESS_BY_INVOICETYPE',
  UPDATED_ADDRESS_BY_INVOICETYPE: 'UPDATED_ADDRESS_BY_INVOICETYPE',
  FAILED_UPDATE_ADDRESS_BY_INVOICETYPE: 'FAILED_UPDATE_ADDRESS_BY_INVOICETYPE',
};
