export const AUTH_ACTIONS = {
  FETCH_AUTH: 'FETCH_AUTH',
  FETCHED_AUTH: 'FETCHED_AUTH',
  FAILED_FETCH_AUTH: 'FAILED_FETCH_AUTH',
  SET_AUTH: 'SET_AUTH',
  LOGOUT: 'LOGOUT',
  UPDATE_USER: 'UPDATE_USER',
  SET_FCM_TOKEN: 'SET_FCM_TOKEN',
};
