export const CATEGORIES_ACTIONS = {
  FETCH_CATEGORY_BY_CODE: 'FETCH_CATEGORY_BY_CODE',
  FETCHED_CATEGORY_BY_CODE: 'FETCHED_CATEGORY_BY_CODE',
  FAILED_FETCH_CATEGORY_BY_CODE: 'FAILED_FETCH_CATEGORY_BY_CODE',
};
