export const ORDER_ACTIONS = {
  FETCH_ORDERS: 'FETCH_ORDERS',
  FETCHED_ORDERS: 'FETCHED_ORDERS',
  FAILED_FETCH_ORDERS: 'FAILED_FETCH_ORDERS',

  FETCH_ORDER_DETAILS: 'FETCH_ORDER_DETAILS',
  FETCHED_ORDER_DETAILS: 'FETCHED_ORDER_DETAILS',
  FAILED_FETCH_ORDER_DETAILS: 'FAILED_FETCH_ORDER_DETAILS',

  EMPTY_ORDERS: 'EMPTY_ORDERS',
  SET_ORDERED_TIME: 'SET_ORDERED_TIME',
};
