export const PAYMENT_ACTIONS = {
  FETCH_PAYMENT_METHODS: 'FETCH_PAYMENT_METHODS',
  FETCHED_PAYMENT_METHODS: 'FETCHED_PAYMENT_METHODS',
  FAILED_FETCHED_PAYMENT_METHODS: 'FAILED_FETCHED_PAYMENT_METHODS',
};
