export const PRODUCTS_ACTIONS = {
  FETCH_PRODUCT: 'FETCH_PRODUCT',
  FETCHED_PRODUCT: 'FETCHED_PRODUCT',
  FAILED_FETCH_PRODUCT: 'FAILED_FETCH_PRODUCT',
  FETCH_PRODUCT_REVIEW: 'FETCH_PRODUCT_REVIEW',
  FETCHED_PRODUCT_REVIEW: 'FETCHED_PRODUCT_REVIEW',
  FAILED_FETCH_PRODUCT_REVIEW: 'FAILED_FETCH_PRODUCT_REVIEW',
  FETCH_PRODUCT_QUESTION: 'FETCH_PRODUCT_QUESTION',
  FETCHED_PRODUCT_QUESTION: 'FETCHED_PRODUCT_QUESTION',
  FAILED_FETCH_PRODUCT_QUESTION: 'FAILED_FETCH_PRODUCT_QUESTION',
  SET_SHIPPING_VALUE: 'SET_SHIPPING_VALUE',
  SET_SIMILAR_PRODUCTS: 'SET_SIMILAR_PRODUCTS',
  SET_RELATED_CATEGORIES: 'SET_RELATED_CATEGORIES',
  SET_PRODUCT_EMI: 'SET_PRODUCT_EMI',
  SET_PRODUCT_OFFER: 'SET_PRODUCT_OFFER',
  SET_FBT_PRODUCTS: 'SET_FBT_PRODUCTS',
};

export const RATINGS = [
  {star: 5, key: 'five_star_count', class: 'greenShade'},
  {star: 4, key: 'four_star_count', class: 'LightGreenShade'},
  {star: 3, key: 'three_star_count', class: 'YellowShade'},
  {star: 2, key: 'two_star_count', class: 'OrangeShade'},
  {star: 1, key: 'one_star_count', class: 'RedShade'},
];
