export const RECENTLY_VIEWED_ACTIONS = {
  FETCH_RECENTLY_VIEWED: 'FETCH_RECENTLY_VIEWED',
  FETCHED_RECENTLY_VIEWED: 'FETCHED_RECENTLY_VIEWED',
  FAILED_FETCH_RECENTLY_VIEWED: 'FAILED_FETCH_RECENTLY_VIEWED',
  FETCH_SET_RECENTLY_VIEWED: 'FETCH_SET_RECENTLY_VIEWED',
  FETCHED_SET_RECENTLY_VIEWED: 'FETCHED_SET_RECENTLY_VIEWED',
  FAILED_FETCH_SET_RECENTLY_VIEWED: 'FAILED_FETCH_SET_RECENTLY_VIEWED',
};
