export const WISHLIST_ACTIONS = {
  FETCH_WISHLIST: 'FETCH_WISHLIST',
  FETCHED_WISHLIST: 'FETCHED_WISHLIST',
  FAILED_FETCH_WISHLIST: 'FAILED_FETCH_WISHLIST',
  UPDATE_WISHLIST: 'UPDATE_WISHLIST',
  FAILED_UPDATE_WISHLIST: 'FAILED_UPDATE_WISHLIST',
  UPDATED_WISHLIST: 'UPDATED_WISHLIST',
};
