import {Dimensions, StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import colors from '../../redux/constants/colors';

const styles = StyleSheet.create({
  modalWrap: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EFEFF4',
    padding: Dimension.padding25,
    alignItems: 'center',
  },
  modalcoupenImg: {width: Dimension.width38, height: Dimension.width38},
  appliedCpnText: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginVertical: Dimension.margin15,
  },
  appliedCpnText: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginVertical: Dimension.margin15,
  },
  saveAmounttext: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font24,
    fontFamily: Dimension.CustomRobotoBold,
    fontWeight: 'bold',
  },
  greenText: {
    color: colors.GreenColor,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginTop: Dimension.margin15,
  },
  normalText: {
    color: colors.lightGrayText,
    fontSize: Dimension.font10,
    fontFamily: Dimension.CustomRegularFont,
  },
  modalWrap: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EFEFF4',
    padding: Dimension.padding25,
    alignItems: 'center',
  },
  headerView: {
    zIndex: 1000,
    elevation: 1,
    flexDirection: 'row',
    height: 60,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#EFEFF4',
    paddingHorizontal: Dimension.padding10,
    justifyContent: 'space-between',
    position: 'relative',
    backgroundColor: '#fff',
  },
  filtHeading: {
    marginLeft: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font12,
    paddingTop: 5,
    color: colors.PrimaryTextColor,
  },
  topDeliveryAddress: {
    padding: 10,
    borderColor: colors.ProductBorderColor,
    borderWidth: 2,
    marginVertical: 12,
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 4,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  topDeliveryAddressTxt: {
    color: 'red',
    alignSelf: 'center',
    color: colors.RedThemeColor,
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomBoldFont,
    marginLeft: 5,
    textTransform: 'uppercase',
  },
  headerFlex: {flexDirection: 'row'},
  bottomHeaderWrap: {backgroundColor: '#fff', marginTop: -3},
  bottomHeaderTop: {flexDirection: 'row'},
  textWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: Dimension.padding12,
  },
  headerTitle: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font12,
    color: colors.green2,
    textTransform: 'uppercase',
  },
  grayheaderTitle: {
    fontFamily: Dimension.CustomMediumFont,
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    textTransform: 'uppercase',
  },
  ProgressBar: {flexDirection: 'row', width: '100%'},
  greenLine: {backgroundColor: colors.green2, height: 2, marginVertical: 4},
  grayLine: {backgroundColor: colors.gray2, height: 2, marginVertical: 4},
  greenDot: {
    width: Dimension.padding10,
    height: Dimension.padding10,
    backgroundColor: colors.green2,
    borderRadius: Dimension.padding10,
  },
  grayDot: {
    width: Dimension.padding10,
    height: Dimension.padding10,
    backgroundColor: colors.gray2,
    borderRadius: Dimension.padding10,
  },
  Pwidth1: {width: '8%'},
  Pwidth2: {width: '38%'},
  checkOutPage: {paddingHorizontal: Dimension.padding12, flex: 1},
  gstCard: {
    backgroundColor: '#fff',
    padding: Dimension.padding10,
    borderRadius: Dimension.borderRadius6,
    shadowColor: '#888',
    flexDirection: 'row',
    marginTop: 20,
    // marginBottom: 15,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 4,
  },
  checkBox: {marginRight: 15},
  getGstInvTitle: {
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font12,
    marginBottom: -Dimension.margin2,
    color: colors.PrimaryTextColor,
  },
  getGstInvSubTitle: {
    fontSize: Dimension.font11,
    color: colors.lightGrayText,
    fontFamily: Dimension.CustomRegularFont,
  },
  promoAppliedView: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: Dimension.margin4,
    marginBottom: Dimension.margin12,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: Dimension.padding15,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  promocode: {
    color: colors.green2,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  applyCouponWrap: {
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius6,
    paddingHorizontal: Dimension.padding12,
    marginBottom: Dimension.padding10,
    flexDirection: 'row',
    paddingVertical: Dimension.padding12,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  couponIcon: {
    color: colors.green2,
    fontFamily: Dimension.CustomSemiBoldFont,
  },
  applyText: {
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font16,
    paddingTop: 2,
    marginLeft: 20,
    color: colors.PrimaryTextColor,
  },
  leftPromoArea: {flexDirection: 'row', alignItems: 'center'},
  ticketIcon: {color: colors.green2, marginRight: Dimension.margin15},
  promoSubText: {
    color: colors.lightGrayText,
    fontSize: Dimension.font11,
    marginTop: -Dimension.margin2,
    fontFamily: Dimension.CustomRegularFont,
  },
  viewAllOffers: {flexDirection: 'row'},
  arrowrightIcon: {
    fontSize: Dimension.font24,
    marginRight: 10,
    color: colors.PrimaryTextColor,
  },

  paymentWrap: {
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginHorizontal: Dimension.margin12,
  },
  payHeading: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    paddingHorizontal: Dimension.padding12,
    paddingVertical: Dimension.padding10,
    borderBottomWidth: 1,
    borderBottomColor: colors.ProductBorderColor,
  },
  amountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.ProductBorderColor,
    paddingVertical: Dimension.padding8,
    paddingHorizontal: Dimension.padding12,
  },
  amtTextLabel: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
    color: colors.PrimaryTextColor,
  },
  noBorder: {borderBottomWidth: 0},
  totalAmountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.ProductBorderColor,
    paddingVertical: Dimension.padding10,
    paddingHorizontal: Dimension.padding12,
  },
  amtText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomRobotoRegular,
    color: colors.PrimaryTextColor,
  },
  greenAmtText: {
    color: colors.GreenColor,
  },
  totalAmtTextLabel: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
  },
  totalAmtText: {
    fontSize: Dimension.font16,
    fontFamily: Dimension.CustomRobotoBold,
    color: colors.PrimaryTextColor,
  },
  redBtn: {
    backgroundColor: colors.RedThemeColor,
    height: Dimension.height40,
    width: '50%',
    borderRadius: Dimension.borderRadius6,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  redBtnText: {
    color: '#fff',
    fontFamily: Dimension.CustomBoldFont,
    fontSize: Dimension.font16,
  },
  bottomAction: {
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: Dimension.padding5,
    justifyContent: 'space-between',
    position: 'absolute',
    width: '100%',
    bottom: 0,
    flex: 1,
  },
  leftAmt: {
    width: '50%',
    justifyContent: 'center',
    paddingLeft: Dimension.padding15,
  },
  amtWrap: {flexDirection: 'row'},
  payable: {
    color: colors.lightGrayText,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomRegularFont,
  },
  infoIcon: {color: colors.BlueText, marginLeft: Dimension.padding10},
  totalAmtinBottom: {
    color: colors.PrimaryTextColor,
    fontSize: Dimension.font18,
    fontFamily: Dimension.CustomRobotoBold,
  },
  checkoutPage: {paddingBottom: 70},
  card: {
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius6,
    paddingHorizontal: Dimension.padding12,
    paddingVertical: Dimension.padding15,
    marginBottom: Dimension.padding10,
    paddingBottom: 0,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  addrTitle: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    fontFamily: Dimension.CustomMediumFont,
  },
  addrWrap: {
    marginTop: Dimension.margin15,
  },
  addrListWrap: {
    marginVertical: 12,
    backgroundColor: '#fff',
    borderRadius: Dimension.borderRadius6,
    padding: Dimension.padding12,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 1,
  },
  addrCustName: {
    color: '#000',
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomBoldFont,
    marginBottom: 5,
  },
  fullAddr: {
    color: '#000',
    fontFamily: Dimension.CustomRegularFont,
    fontSize: Dimension.font11,
  },
  changeAddrBtn: {
    backgroundColor: colors.LightRedThemeColor,
    padding: 8,
    width: '100%',
    borderRadius: Dimension.borderRadius6,
    marginTop: Dimension.margin10,
  },
  changeAddrText: {
    color: colors.RedThemeColor,
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    alignSelf: 'center',
  },
  selectAddPage: {flex: 1, position: 'relative'},
  scrollViewPg: {flex: 1, marginBottom: 57},
  impUpdateCart: {
    borderColor: colors.orangeShade,
    borderWidth: 1,
    marginTop: Dimension.margin15,
    // marginBottom: Dimension.margin15,
    borderRadius: Dimension.borderRadius6,
    padding: Dimension.padding12,
    backgroundColor: '#FFEBE0',
  },
  impUpdateCartText: {flexDirection: 'row', justifyContent: 'space-between'},
  msgHeading: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    marginTop: 2,
  },
  cartUpdateMsgList: {flexDirection: 'row', alignItems: 'flex-start'},
  dot: {
    width: 6,
    height: 6,
    marginRight: 8,
    borderRadius: Dimension.borderRadius16,
    backgroundColor: colors.PrimaryTextColor,
    marginTop: 5,
  },
  listText: {
    flexDirection: 'column',
    marginBottom: Dimension.margin4,
    paddingRight: Dimension.padding10,
  },
  listBlueText: {
    fontSize: Dimension.font12,
    color: colors.BlueText,
    fontFamily: Dimension.CustomRegularFont,
  },
  listGreyText: {
    fontSize: Dimension.font12,
    color: colors.PrimaryTextColor,
    marginLeft: -Dimension.margin6,
    fontFamily: Dimension.CustomRobotoRegular,
  },
  arrowIcon: {fontSize: Dimension.font20, color: colors.PrimaryTextColor},
});

export default styles;
