import {Dimensions, StyleSheet} from 'react-native';
import Dimension from '../../redux/constants/dimensions';
import colors from '../../redux/constants/colors';

const styles = StyleSheet.create({
  cartItemCount: {
    backgroundColor: colors.RedThemeColor,
    borderRadius: Dimension.borderRadius4,
    paddingVertical: Dimension.padding2,
    color: '#fff',
    fontSize: Dimension.font11,
    fontFamily: Dimension.CustomMediumFont,
    position: 'absolute',
    justifyContent: 'center',
    textAlign: 'center',
    alignContent: 'center',
    paddingHorizontal: Dimension.padding5,
    right: -5,
    top: -10,
  },
  headerView: {
    flexDirection: 'row',
    height: 60,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#EFEFF4',
    paddingHorizontal: Dimension.padding10,
    justifyContent: 'space-between',
    position: 'relative',
    backgroundColor: '#fff',
  },
  filtHeading: {
    marginLeft: 10,
    fontFamily: Dimension.CustomSemiBoldFont,
    fontSize: Dimension.font12,
    paddingTop: 5,
    color: colors.PrimaryTextColor,
  },
  headerFlex: {flexDirection: 'row'},
  viewTypeWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    paddingVertical: Dimension.padding10,
    paddingHorizontal: Dimension.padding12,
  },

  productCount: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomMediumFont,
    color: colors.PrimaryTextColor,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: Dimension.margin5,
  },
  viewTypeIcon: {color: colors.PrimaryTextColor},
  listViewCard: {
    position: 'relative',
    marginTop: -10,
    marginBottom: -8,
    paddingVertical: Dimension.padding10,
  },
  wishListPg: {flex: 1},
  cartBtn: {
    position: 'absolute',
    right: 40,
    zIndex: 2,
    bottom: 35,
    backgroundColor: colors.RedThemeColor,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Dimension.padding15,
    borderRadius: Dimension.borderRadius4,
  },
  cartBtnText: {
    fontSize: Dimension.font12,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: '#fff',
  },
  flatListView: {marginVertical: 15},
  gridViewCard: {
    flexBasis: '50%',
    paddingHorizontal: Dimension.padding6,
    position: 'relative',
    marginBottom: Dimension.padding12,
  },
  flatGridView: {
    flexDirection: 'column',
    flexWrap: 'wrap',
    paddingHorizontal: Dimension.padding6,
    marginVertical: Dimension.padding10,
  },
  wishlistIcon: {
    position: 'absolute',
    right: 15,
    zIndex: 1,
    top: 10,
    marginBottom: 10,
  },
  heartIcon: {color: colors.RedThemeColor},
  cartBtnTextForGrid: {
    width: '100%',
    backgroundColor: colors.RedThemeColor,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Dimension.padding15,
    borderBottomLeftRadius: Dimension.borderRadius8,
    borderBottomRightRadius: Dimension.borderRadius8,
    bottom: 0,
    position: 'absolute',
    left: Dimension.padding6,
  },
  noOrders: {
    paddingHorizontal: Dimension.padding15,
    flex: 1,
    // alignSelf: 'center',
  },
  whiteBgWithImage: {
    backgroundColor: '#fff',
    padding: Dimension.padding15,
    alignItems: 'center',
    paddingBottom: Dimension.padding30,
    borderRadius: Dimension.borderRadius16,
  },
  noOrderImage: {width: Dimension.width185, height: Dimension.width150},
  noOrderText: {
    fontSize: Dimension.font14,
    fontFamily: Dimension.CustomSemiBoldFont,
    color: colors.PrimaryTextColor,
    marginTop: Dimension.margin10,
    alignSelf: 'center',
    textAlign: 'center',
    marginBottom: Dimension.margin30,
  },
});

export default styles;
